TheTrackerCouncil/SMZ3Randomizer

Randomizer.App/TrackerLocationSyncer.cs
Randomizer.App/ViewModels/LocationViewModel.cs
Randomizer.App/ViewModels/TrackerMapLocationViewModel.cs
Randomizer.App/ViewModels/TrackerMapViewModel.cs
Randomizer.App/ViewModels/TrackerViewModel.cs
Randomizer.App/Windows/TrackerLocationsWindow.xaml.cs
Randomizer.App/Windows/TrackerMapWindow.xaml
Randomizer.App/Windows/TrackerMapWindow.xaml.cs
Randomizer.App/Windows/TrackerWindow.xaml.cs

To make this and other changes going forward easier, I made an intermediary class to access data to help keep the location and map windows synced up

Added location clearing via the map

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.App/TrackerLocationSyncer.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs

Fixed an issue where keysanity logic was accidentally inverted when determining item accessiblity in dungeons.

Fixed keysanity logic

---

src/Randomizer.SMZ3/Regions/Zelda/EasternPalace.cs
src/Randomizer.SMZ3/Regions/Zelda/HyruleCastle.cs
src/Randomizer.SMZ3/Regions/Zelda/PalaceOfDarkness.cs

Adjusts fire rod logic for dark rooms to be consistent with logic in ALTTPR.

Advanced fire rod logic

---

src/Randomizer.App/Windows/TrackerWindow.xaml
src/Randomizer.App/Windows/TrackerWindow.xaml.cs
src/Randomizer.App/appSettings.Development.json
src/Randomizer.SMZ3.Tracking/Configuration/HintsConfig.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/TrackerEventArgs.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
src/Randomizer.SMZ3.Tracking/tracker.json

Worked on some notes I had written down from watching past streams.
Mostly minor config tweaks and jokes, but also:
- Added a status bar item that shows the last recognized phrase.
- Added item name to hints when asking about an already cleared location.
- Fixed Tracker saying "But you already have that" when tracking a boss after clearing the item that the boss drops.
- Fixed undoing "Clear X treasures" only adding back 1 treasure.

Stream feedback

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.App/Windows/GenerateRomWindow.xaml
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/locations.json

Just a small handful of changes after testing with the new respin patch

Misc. changes

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj

Updated version to 3.3.3

---

src/Randomizer.App/Windows/AboutWindow.xaml
src/Randomizer.App/Windows/AboutWindow.xaml.cs
src/Randomizer.SMZ3.Tracking/Configuration/HintsConfig.cs
src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
src/Randomizer.SMZ3.Tracking/locations.json
src/Randomizer.SMZ3.Tracking/tracker.json

- Added more phrases for Tracker.
- When asking what's at a location, tracker will now tell you whether it's good or not right away.
- Tracker will respect the spoiler threshold setting when tracking all items in an area.

Stream feedback & ideas

---

src/Randomizer.SMZ3/FileData/Patches/CasualSMPatch.cs

I didn't really know what I was doing with the offsets before so I looked at other offsets and copied that. Pink recently told me how infinite space jump was actually supposed to work so now that I know better, I know what I did wrong.

Fixed infinite space jump patch

---

CasRandomizer.sln
src/Randomizer.App/App.xaml.cs
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.App/ViewModels/GeneralOptions.cs
src/Randomizer.App/Windows/OptionsWindow.xaml
src/Randomizer.App/Windows/OptionsWindow.xaml.cs
src/Randomizer.App/Windows/RomListWindow.xaml.cs
src/Randomizer.App/Windows/TrackerWindow.xaml.cs
src/Randomizer.SMZ3.ChatIntegration/ChatMessage.cs
src/Randomizer.SMZ3.ChatIntegration/IChatAuthenticationService.cs
src/Randomizer.SMZ3.ChatIntegration/IChatClient.cs
src/Randomizer.SMZ3.ChatIntegration/MessageReceivedEventArgs.cs
src/Randomizer.SMZ3.ChatIntegration/MessageReceivedEventHandler.cs
src/Randomizer.SMZ3.ChatIntegration/OAuthChatAuthenticationService.cs
src/Randomizer.SMZ3.ChatIntegration/Randomizer.SMZ3.ChatIntegration.csproj
src/Randomizer.SMZ3.Tracking/Configuration/ChatConfig.cs
src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
src/Randomizer.SMZ3.Tracking/Randomizer.SMZ3.Tracking.csproj
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/TrackerFactory.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/TrackerModuleFactory.cs
src/Randomizer.SMZ3.Tracking/tracker.json
src/Randomizer.SMZ3.Twitch/Randomizer.SMZ3.Twitch.csproj
src/Randomizer.SMZ3.Twitch/TwitchAuthenticationService.cs
src/Randomizer.SMZ3.Twitch/TwitchChatClient.cs
src/Randomizer.SMZ3.Twitch/TwitchChatMessage.cs

Added the ability for Tracker to say hello to chat and respond to people saying "Hey tracker". Fully configurable with regex expressions for recognition and user name pronunciation replacements.
Remaining for this PR:

Twitch integration

---

src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/locations.json

Fixed multiple dungeon-clearing issues

---

src/Randomizer.SMZ3.ChatIntegration/ChatMessage.cs
src/Randomizer.SMZ3.ChatIntegration/IChatClient.cs
src/Randomizer.SMZ3.Tracking/Configuration/ChatConfig.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
src/Randomizer.SMZ3.Tracking/tracker.json
src/Randomizer.SMZ3.Twitch/TwitchAuthenticationService.cs
src/Randomizer.SMZ3.Twitch/TwitchChatClient.cs
src/Randomizer.SMZ3.Twitch/TwitchChatMessage.cs

Adds support for the GT Guessing Game is Twitch integration is enabled. Adds voice commands to start the guessing game, close the floor and announce the winner. Moderators can also close the floor by saying "CLOSE" in chat.
Requires new Twitch permissions to work correctly.

Ganon's Tower Big Key Guessing Game

---

src/Randomizer.App/Windows/OptionsWindow.xaml.cs
src/Randomizer.SMZ3.ChatIntegration/IChatAuthenticationService.cs
src/Randomizer.SMZ3.ChatIntegration/OAuthChatAuthenticationService.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
src/Randomizer.SMZ3.Twitch/TwitchAuthenticationService.cs
src/Randomizer.SMZ3.Twitch/TwitchChatAPI.cs

Also added some error handling

Addressing pull request comments

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/BossTrackingModule.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
src/Randomizer.SMZ3.Tracking/tracker.json
src/Randomizer.SMZ3/ILogic.cs
src/Randomizer.SMZ3/Logic.cs
src/Randomizer.SMZ3/Regions/SuperMetroid/Maridia/InnerMaridia.cs
src/Randomizer.Shared/Models/LogicConfig.cs
tests/Randomizer.SMZ3.Tests/LogicTests/LogicConfigTests.cs

- Increased fequency of polling viewers for content updates from 25% of the time to 33% of the time
- Added logic config for the left sand pit requiring the spring ball and hi jump boots
- Tracking bosses as quick killed or without taking damage will add content

Stream Updates

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.SMZ3.ChatIntegration/IChatClient.cs
src/Randomizer.SMZ3.Tracking/Configuration/ChatConfig.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/AutoTrackerModule.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
src/Randomizer.SMZ3.Tracking/tracker.json
src/Randomizer.SMZ3.Twitch/TwitchChatAPI.cs
src/Randomizer.SMZ3.Twitch/TwitchChatClient.cs

During the stream there were a few Twitch integration issues that bubbled up due to what we believe were some issues on Twitch's side since several of us were having lots of buffering issues around the time everything started.
Effectively according to the logs it seemed like around 30 minutes into the stream Tracker "reconnected" to the Twitch chat. I put that in quotes as Tracker didn't fully reconnect as she wasn't picking up any messages from chat after that point. This ultimately ended up in Tracker dying when betus asked what was guessed for the GT guessing game because at that point she tries to send a chat message, but that failed due to not being in a channel (again, not fully reconnected). Unfortunately that error wasn't being handled, thus leading to the crash.
So, I'm handling …

Twitch Integration Fixes

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs

Happened in Pink's stream. Not sure how I got the previous coordinates for ice breaker.

Fixing ice breaker going off too early

---

setup/randomizer.app.iss
src/Randomizer.App/Windows/TrackerWindow.xaml.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/TrackerModuleFactory.cs

- Updated inno setup file to work with both 32bit and 64bit
- Handling errors with modules loading to allow tracker to open for manual tracking

Compatibility Updates

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj

Ended up not having time to make any other updates, so just updating version number for the release. I have a draft of the release up if you want to proofread it.

Updating version number

---

src/Randomizer.SMZ3.Tracking/AutoTracking/USB2SNESConnector.cs
src/Randomizer.SMZ3/Regions/Zelda/ThievesTown.cs

- Fixed issue with Blind's item not tracking
- Hopefully fixed issue with USB2SNES connections reading memory too early and marking off all the SM items

More bug fixes

---

src/Randomizer.App/RomGenerator.cs
src/Randomizer.App/ViewModels/GeneratedRomsViewModel.cs
src/Randomizer.App/Windows/RomListWindow.xaml
src/Randomizer.App/Windows/RomListWindow.xaml.cs
src/Randomizer.App/Windows/TrackerWindow.xaml.cs
src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTrackerMetroidState.cs
src/Randomizer.SMZ3.Tracking/AutoTracking/MetroidStateChecks/ChangedMetroidRegion.cs
src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
src/Randomizer.SMZ3.Tracking/HistoryService.cs
src/Randomizer.SMZ3.Tracking/IHistoryService.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/TrackerFactory.cs
src/Randomizer.SMZ3.Tracking/TrackerServiceCollectionExtensions.cs
src/Randomizer.SMZ3.Tracking/TrackerState.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/ItemTrackingModule.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/MetaModule.cs
src/Randomizer.SMZ3.Tracking/tracker.json
src/Randomizer.Shared/Enums/HistoryEventType.cs
src/Randomizer.Shared/Migrations/20220706171503_History.Designer.cs
src/Randomizer.Shared/Migrations/20220706171503_History.cs
src/Randomizer.Shared/Migrations/20220707124452_UndoHistory.Designer.cs
src/Randomizer.Shared/Migrations/20220707124452_UndoHistory.cs
src/Randomizer.Shared/Models/RandomizerContext.cs
src/Randomizer.Shared/Models/TrackerHistoryEvent.cs
src/Randomizer.Shared/Models/TrackerState.cs

Pretty rough draft of changes, but wanted to get this out there somewhat for initial general implementation. Need to do some documenting and clean up.

Progression History

---

src/Randomizer.SMZ3.Tracking/locations.json
src/Randomizer.SMZ3.Tracking/tracker.json
tests/Randomizer.SMZ3.Tests/JsonTests.cs
tests/Randomizer.SMZ3.Tests/Randomizer.SMZ3.Tests.csproj

This started out with some random ideas I got from reviewing pull requests but ended up being mostly about adding room descriptions as location names.
I'm creating this as a draft PR in case you have any suggestions of your own I could add while I'm here.

JSON stuff

---

src/Randomizer.App/App.xaml.cs
src/Randomizer.App/Windows/RomListWindow.xaml.cs

Fixed crash when generating a rom for the second time

---

src/Randomizer.SMZ3.Tracking/Configuration/ConfigTypes/ChatConfig.cs
src/Randomizer.SMZ3.Tracking/Configuration/IMergeable.cs
src/Randomizer.SMZ3.Tracking/Configuration/Yaml/BCU/responses.yml
src/Randomizer.SMZ3.Tracking/Configuration/Yaml/Sassy/responses.yml
src/Randomizer.SMZ3.Tracking/Configuration/Yaml/Templates/responses.yml
src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
src/Randomizer.SMZ3.Twitch/TwitchChatAPI.cs

Please enjoy these barely tested GT guessing game enhancements.
Resolves #189 and also let's Tracker join in with her own guesses.
Until #191 is implemented, Tracker's death rattle will only go off after winners are announced.

Ganon's Tower Big Key Guessing Game Enhancements

---

src/Randomizer.SMZ3/Generation/PlandoConfig.cs

Moving LogicConfig to top to hopefully help avoid accidental spoilers

Updating plando config file

---

src/Randomizer.App/Windows/OptionsWindow.xaml
src/Randomizer.App/Windows/OptionsWindow.xaml.cs
src/Randomizer.App/Windows/RomListWindow.xaml.cs
src/Randomizer.SMZ3.ChatIntegration/IChatAuthenticationService.cs
src/Randomizer.SMZ3.ChatIntegration/Models/TwitchAPIResponse.cs
src/Randomizer.SMZ3.ChatIntegration/OAuthChatAuthenticationService.cs
src/Randomizer.SMZ3.Twitch/Models/ValidateResponse.cs
src/Randomizer.SMZ3.Twitch/TwitchAuthenticationService.cs
src/Randomizer.SMZ3.Twitch/TwitchChatAPI.cs

Some long-outstanding improvements to the Twitch login thing. The token is now validated on startup, no longer being shown in Options and has a Log out button when logged in.
The token is not encrypted yet, though.

Twitch login improvements

---

src/Randomizer.App/App.xaml.cs
src/Randomizer.App/RomGenerator.cs
src/Randomizer.App/Windows/TrackerWindow.xaml.cs
src/Randomizer.Data/Configuration/ConfigTypes/SpoilerConfig.cs
src/Randomizer.Data/Configuration/Yaml/Templates/responses.yml
src/Randomizer.Data/Options/Config.cs
src/Randomizer.Data/Options/RandomizerOptions.cs
src/Randomizer.Data/Services/TrackerStateService.cs
src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
src/Randomizer.SMZ3.Tracking/Services/IItemService.cs
src/Randomizer.SMZ3.Tracking/Services/IWorldService.cs
src/Randomizer.SMZ3.Tracking/Services/ItemService.cs
src/Randomizer.SMZ3.Tracking/Services/WorldService.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/ItemTrackingModule.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
src/Randomizer.SMZ3/Generation/SeedData.cs
src/Randomizer.SMZ3/Generation/Smz3GeneratedRomLoader.cs
src/Randomizer.SMZ3/Generation/Smz3Plandomizer.cs
src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
src/Randomizer.SMZ3/RandomizerServiceCollectionExtensions.cs
src/Randomizer.Shared/Migrations/20221018032415_MultiworldAutotracked.Designer.cs
src/Randomizer.Shared/Migrations/20221018032415_MultiworldAutotracked.cs
src/Randomizer.Shared/Models/TrackerLocationState.cs

Closes #233 
These changes are to get tracker working with multiworld. From my testing, it seems to work as expected though I'm sure there are still some cases that will need to be addressed once proper multiworld is up and running.
Here are the major changes for this:
- Instead of a single config being stored in the database, multiple configs can now be stored for each of the worlds.
- When loading tracker, worlds will be generated based off of the config(s) stored in the database. All of the items, dungeons, and bosses were being set after the fact already when loading the tracker state. Before it was creating the world randomly and then overwriting it, so this just skips the random world generation step.
- Updated the database and auto tracker to keep track of if a location has been …

Tracker Updates for Multiworld

---

src/Randomizer.Data/Configuration/Yaml/Sassy/items.yml

I keep hearing this line and wondering if "99" would be better. Maybe not?

Subtracted the blue rupee that was just picked up from this line

---

src/Randomizer.Data/Configuration/Yaml/Sassy/items.yml

I thought this was pretty funny, but will totally understand if the Arrested Development reference is too niche and/or out-of-place

Added line for tracking single arrow

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.Data/Configuration/Yaml/Sassy/items.yml
src/Randomizer.Data/Logic/LogicConfig.cs
src/Randomizer.Data/WorldData/Regions/Zelda/LightWorld/LightWorldNorthEast.cs
src/Randomizer.SMZ3/FileData/Patcher.cs
tests/Randomizer.SMZ3.Tests/LogicTests/LogicConfigTests.cs

Fix for requesting 0 hints

---

src/Randomizer.App/Controls/FileSystemInput.xaml.cs
src/Randomizer.App/Windows/OptionsWindow.xaml

Fixes #248
Archipelago checks hashes for both ALttP and SM, so I used the same hashes as them.

Adding rom validation

---

src/Randomizer.App/App.xaml.cs

Fixes #243
Note that there could be some issues still with folks that have unusual monitor combinations (like me), but I think this should cover 99% of scenarios were this could happen.

Move windows back into bounds on launch

---

src/Randomizer.Data/Options/CasPatches.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs

Fixes #204 
Also tweaking the display name for the quarter magic and filled potions option.

Auto clear dungeons

---

src/Randomizer.Data/Options/CasPatches.cs
src/Randomizer.Data/Options/ItemSettingOptions.yml
src/Randomizer.Data/WorldData/World.cs
src/Randomizer.Data/WorldData/WorldItemPools.cs
src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/ViewedMap.cs
src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/ViewedMedallion.cs
src/Randomizer.SMZ3/FileData/Patcher.cs
tests/Randomizer.SMZ3.Tests/LogicTests/RandomizerTests.cs

Fixes #205 
This also fixes an issue that could come up with viewing maps if opening the map super quickly when changing games or between light/dark world.
Also went ahead and split out randomized bottles and quarter magic per betus's request.

"Look at This" command for medallions

---

src/Randomizer.Data/Configuration/Yaml/BCU/responses.yml

(In honor of me finally watching the Dark Seed 2 RP)

New response for enabling spoilers

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.App/RomGenerator.cs
src/Randomizer.Data/Options/ItemSettingOptions.yml
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs

Fixes #300 
Fixes #299 
Fixes #297 
Fixes #295

v9.0.0 Bug Fixes

---

src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.Data/Configuration/ConfigFiles/LocationConfig.cs

Okay, I think I've got this in the right spot. Verified that I can ask Tracker for spoilers for both "Misery Mire Big Key Chest" and "Misery Mire Cutscene Chest", which seems like it means it's working!

Added "Misery Mire Cutscene Chest" alias #301

---

src/Randomizer.Data/Configuration/Yaml/BCU/items.yml
src/Randomizer.Data/Configuration/Yaml/Sassy/items.yml
src/Randomizer.Data/Configuration/Yaml/Sassy/locations.yml
src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml
src/Randomizer.SMZ3.Twitch/Models/TwitchPoll.cs

So turns out Twitch polls are stupid. Sometimes polls seem to come back with the status "terminated" for whatever reason despite lasting the full 60 seconds and having votes come in. So, instead I'm just having tracker check to see if votes were found to determine if the polls was successful or not.
Also added a few random tracker comments.

Twitch poll fix and additional responses

---

src/Randomizer.Data/WorldData/Location.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/BlueBrinstar.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/GreenBrinstar.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/KraidsLair.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/PinkBrinstar.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/RedBrinstar.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Crateria/CentralCrateria.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Crateria/EastCrateria.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Crateria/WestCrateria.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Maridia/InnerMaridia.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Maridia/OuterMaridia.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/LowerNorfairEast.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/LowerNorfairWest.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/UpperNorfairCrocomire.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/UpperNorfairEast.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/UpperNorfairWest.cs
src/Randomizer.Data/WorldData/Regions/SuperMetroid/WreckedShip.cs
src/Randomizer.Data/WorldData/Regions/Zelda/DarkWorld/DarkWorldNorthEast.cs
src/Randomizer.Data/WorldData/Regions/Zelda/DarkWorld/DarkWorldNorthWest.cs
src/Randomizer.Data/WorldData/Regions/Zelda/DarkWorld/DarkWorldSouth.cs
src/Randomizer.Data/WorldData/Regions/Zelda/LightWorld/LightWorldNorthEast.cs
src/Randomizer.Data/WorldData/Regions/Zelda/LightWorld/LightWorldNorthWest.cs
src/Randomizer.Data/WorldData/Regions/Zelda/LightWorld/LightWorldSouth.cs
src/Randomizer.Data/WorldData/World.cs

IHasLocations.AlsoKnownAs stays intact. All tests pass and I confirmed that asking Tracker for spoilers for the alternate names still works.

#301 Clean-up: Removed Location.AlternateNames

---

src/Randomizer.Multiplayer.Server/GameManager.cs
src/Randomizer.Multiplayer.Server/Migrations/20230621133443_DeathLink.Designer.cs
src/Randomizer.Multiplayer.Server/Migrations/20230621133443_DeathLink.cs
src/Randomizer.Multiplayer.Server/MultiplayerDbService.cs
src/Randomizer.Multiplayer.Server/Randomizer.Multiplayer.Server.csproj

Because of the location id change, the multiplayer version needs to be updated.

Updating multiplayer version

---

src/Randomizer.SMZ3/Generation/GameHintService.cs

Capitalized "Smith chain"

---

src/Randomizer.Data/Configuration/Yaml/BCU/game.yml
src/Randomizer.Data/Configuration/Yaml/BCU/responses.yml
src/Randomizer.Data/Configuration/Yaml/Rated T for Teen/requests.yml
src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml

Hopefully this isn't seen as mean-spirited!

Cruelly reveling in council unraveling

---

setup/randomizer.app.iss
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.Data/Configuration/Yaml/BCU/responses.yml
src/Randomizer.Data/Configuration/Yaml/Sassy/bosses.yml
src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml

- Updated Inno Setup to pull version from exe
- Tracker line updates

Minor Updates

---

src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.Data/Configuration/ConfigTypes/AutotrackerConfig.cs
src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml
src/Randomizer.Data/Configuration/Yaml/Templates/responses.yml
src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/SpeckyClip.cs

Specky clip

---

.github/workflows/dotnet.yml
setup/CodeDependencies.iss
setup/randomizer.app.iss
src/Randomizer.App/App.xaml.cs
src/Randomizer.App/Controls/MultiRomListPanel.xaml.cs
src/Randomizer.App/Controls/SoloRomListPanel.xaml.cs
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.App/Windows/MultiplayerConnectWindow.xaml.cs
src/Randomizer.App/Windows/MultiplayerStatusWindow.xaml.cs
src/Randomizer.App/Windows/RomListWindow.xaml.cs
src/Randomizer.Data/Randomizer.Data.csproj
src/Randomizer.Multiplayer.Client/MultiplayerClientService.cs
src/Randomizer.Multiplayer.Client/Randomizer.Multiplayer.Client.csproj
src/Randomizer.Multiplayer.Server/Randomizer.Multiplayer.Server.csproj
src/Randomizer.SMZ3.ChatIntegration/Randomizer.SMZ3.ChatIntegration.csproj
src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
src/Randomizer.SMZ3.Tracking/Randomizer.SMZ3.Tracking.csproj
src/Randomizer.SMZ3.Tracking/VoiceCommands/MultiplayerModule.cs
src/Randomizer.SMZ3.Twitch/Randomizer.SMZ3.Twitch.csproj
src/Randomizer.SMZ3/Randomizer.SMZ3.csproj
src/Randomizer.Shared/Randomizer.Shared.csproj
src/Randomizer.Tools/Randomizer.Tools.csproj
tests/Randomizer.SMZ3.Tests/Randomizer.SMZ3.Tests.csproj

Updated .net versions and updated some of the nuget packages.
However, I think the signal r package updates caused issues where some of the messages from the server were now firing on a separate thread, which was causing a lot of multiworld issues. I think this should resolve everything, though.

.net 7 Upgrade

---

src/Randomizer.SMZ3.Tracking/Tracker.cs

Auto track dungeon reward

---

src/Randomizer.App/Controls/FileSystemInput.xaml.cs
src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.App/Windows/MsuTrackWindow.xaml
src/Randomizer.App/Windows/MsuTrackWindow.xaml.cs
src/Randomizer.App/Windows/OptionsWindow.xaml
src/Randomizer.App/Windows/TrackerWindow.xaml
src/Randomizer.App/Windows/TrackerWindow.xaml.cs
src/Randomizer.Data/Options/GeneralOptions.cs
src/Randomizer.Data/Options/MsuTrackDisplayStyle.cs
src/Randomizer.Data/Options/TrackerOptions.cs
src/Randomizer.Data/Randomizer.Data.csproj
src/Randomizer.SMZ3.Tracking/Randomizer.SMZ3.Tracking.csproj
src/Randomizer.SMZ3.Tracking/TrackChangedEventArgs.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs
src/Randomizer.SMZ3.Tracking/VoiceCommands/MsuModule.cs
src/Randomizer.Shared/Randomizer.Shared.csproj

Also updates to the latest MSU Randomizer library which has MSU favoriting and fixes part of the issue that came up with the Slappers MSU today during Pink's stream.

Display current track

---

src/Randomizer.App/SpriteService.cs

Gotta love copy and paste mishaps

Fix bug with losing ship sprite favorites

---

.github/workflows/dotnet.yml
setup/LinuxBuildZipper.ps1
setup/randomizer.app.iss
tests/Randomizer.SMZ3.Tests/MetaTests.cs
tests/Randomizer.SMZ3.Tests/Randomizer.SMZ3.Tests.csproj

- Created GitHub actions to publish builds
- Added test to make sure version number has been updated

GitHub Action Updates

---

src/Randomizer.Data/Configuration/Yaml/Rated T for Teen/responses.yml
src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml

I will not be offended if you all reject this for being too dumb haha

Added a few rare responses for Peg World

---

src/Randomizer.App/Controls/RomListPanel.cs

Apparently copying to clipboard in C# is real stupid.

Fix copy to clipboard issue

---

src/Randomizer.Data/Configuration/ConfigTypes/HintsConfig.cs
src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml
src/Randomizer.Data/Configuration/Yaml/Templates/responses.yml
src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
src/Randomizer.SMZ3/Contracts/IGameHintService.cs
src/Randomizer.SMZ3/Generation/GameHintService.cs
src/Randomizer.Shared/Enums/LocationUsefulness.cs

Updated tracker hints to use the game hint service

---

src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.App/Windows/MultiplayerConnectWindow.xaml
src/Randomizer.Multiplayer.Client/GameServices/MultiplayerGameTypeService.cs
src/Randomizer.Multiplayer.Server/Randomizer.Multiplayer.Server.csproj
src/Randomizer.SMZ3.Tracking/VoiceCommands/MultiplayerModule.cs
src/Randomizer.Shared/Multiplayer/MultiplayerVersion.cs

Fixes #430 
I'm keeping the setting itself around as I figure it can be reused for #431

Force sending of items on completion

---

.github/workflows/dotnet.yml
README.md
setup/LinuxBuildZipper.ps1
src/Randomizer.CrossPlatform/README.md

Add Crossplatform README

---

src/Randomizer.Data/Configuration/ConfigTypes/UILayout.cs
src/Randomizer.Data/Configuration/Configs.cs
src/Randomizer.Data/Configuration/IMergeable.cs

Was able to identify two issues with this:
- It was loading the default profile twice
- If there were duplicates of a UI layout in different files, it would add them twice

Fix duplicate UI layouts

---

src/Randomizer.SMZ3.Tracking/Services/Speech/NullSpeechRecognitionService.cs
src/Randomizer.SMZ3.Tracking/Tracker.cs

Fix disabled SpeechRecognitionMode not working on windows

---

src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/SpeckyClip.cs

As noticed by Pink in today's stream

Prevent multiple Specky Clip comments

---

src/Randomizer.CrossPlatform/Randomizer.CrossPlatform.csproj
src/Randomizer.CrossPlatform/Services/CurrentTrackWindowService.cs
src/Randomizer.CrossPlatform/Services/SharedCrossplatformService.cs
src/Randomizer.CrossPlatform/Services/TrackerWindowService.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerWindowBossPanelViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerWindowDungeonPanelViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerWindowItemPanelViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerWindowPanelViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerWindowViewModel.cs
src/Randomizer.CrossPlatform/Views/AboutWindow.axaml
src/Randomizer.CrossPlatform/Views/CurrentTrackWindow.axaml
src/Randomizer.CrossPlatform/Views/CurrentTrackWindow.axaml.cs
src/Randomizer.CrossPlatform/Views/OptionsWindow.axaml
src/Randomizer.CrossPlatform/Views/SpriteWindow.axaml
src/Randomizer.CrossPlatform/Views/TrackerWindow.axaml
src/Randomizer.CrossPlatform/Views/TrackerWindow.axaml.cs
src/Randomizer.CrossPlatform/Views/TrackerWindowPanel.axaml
src/Randomizer.CrossPlatform/Views/TrackerWindowPanel.axaml.cs
src/Randomizer.Data/Randomizer.Data.csproj
src/Randomizer.PatchBuilder/Randomizer.PatchBuilder.csproj
src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
src/Randomizer.SMZ3.Tracking/Randomizer.SMZ3.Tracking.csproj
src/Randomizer.Shared/Randomizer.Shared.csproj

This implements just the tracker item window.

Cross platform tracker item window

---

src/Randomizer.Data/Configuration/ConfigProvider.cs
src/Randomizer.Data/Options/ItemSettingOptions.cs
src/Randomizer.Data/Services/GenerationSettingsWindowService.cs
src/Randomizer.Data/WorldData/VisibleItems.cs

https://github.com/aaubry/YamlDotNet/discussions/844
This should resolve the intermittent unit test failures that have come up recently.

Remove static YamlDotNet objects

---

src/Randomizer.CrossPlatform/Services/TrackerMapWindowService.cs
src/Randomizer.CrossPlatform/Services/TrackerWindowService.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerMapLocationViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerMapSubLocationViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerMapWindowViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerWindowViewModel.cs
src/Randomizer.CrossPlatform/Views/TrackerMapWindow.axaml
src/Randomizer.CrossPlatform/Views/TrackerMapWindow.axaml.cs
src/Randomizer.CrossPlatform/Views/TrackerWindow.axaml.cs
src/Randomizer.Data/Configuration/ConfigTypes/TrackerMapLocation.cs

Crossplatform map

---

src/Randomizer.CrossPlatform/Services/TrackerLocationsWindowService.cs
src/Randomizer.CrossPlatform/Services/TrackerMapWindowService.cs
src/Randomizer.CrossPlatform/Services/TrackerWindowService.cs
src/Randomizer.CrossPlatform/ViewModels/HintTileViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/LocationViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/MarkedLocationViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/RegionViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerLocationsViewModel.cs
src/Randomizer.CrossPlatform/ViewModels/TrackerMapWindowViewModel.cs
src/Randomizer.CrossPlatform/Views/TrackerLocationsWindow.axaml
src/Randomizer.CrossPlatform/Views/TrackerLocationsWindow.axaml.cs
src/Randomizer.CrossPlatform/Views/TrackerMapWindow.axaml.cs
src/Randomizer.CrossPlatform/Views/TrackerWindow.axaml.cs
src/Randomizer.Shared/Enums/RegionFilter.cs

With this the main changes for the cross platform version are mostly done. Will create one more PR to that will add the auto tracking help window and any random fixes that come from testing more thoroughly.

Crossplatform locations

---

src/Randomizer.Data/WorldData/VisibleItems.yml

Auto-track Bumper Cave Ledge

---

src/Randomizer.CrossPlatform/Randomizer.CrossPlatform.csproj
src/Randomizer.CrossPlatform/Services/TrackerWindowService.cs
src/Randomizer.CrossPlatform/Views/MainWindow.axaml
src/Randomizer.CrossPlatform/Views/MainWindow.axaml.cs
src/Randomizer.CrossPlatform/Views/MultiRomListPanel.axaml.cs
src/Randomizer.CrossPlatform/Views/SoloRomListPanel.axaml.cs
src/Randomizer.CrossPlatform/Views/TrackerWindow.axaml.cs
src/Randomizer.CrossPlatform/Views/TrackerWindowPanel.axaml.cs
src/Randomizer.SMZ3.Tracking/AutoTracking/MetroidStateChecks/Shaktool.cs

- Update to remove Shaktool mode on changing region (in case of a reset)
- Update to support displaying gifs (unfortunately needed to change it to a single large gif instead of a series of gifs)
- Update to reset UI on grabbing an item or defeating a boss
- Fix HC text size when all locations are cleared
- Reload rom list after closing the tracker window

Fixes from Pink's Stream

---

src/Randomizer.Multiplayer.Server/Program.cs
src/Randomizer.Multiplayer.Server/Randomizer.Multiplayer.Server.csproj
src/Randomizer.Multiplayer.Server/appsettings.Development.json
src/Randomizer.Multiplayer.Server/appsettings.json

After moving hosts, I noticed the server doesn't actually write the logs to a file, so I wanted to fix that. Used serilog as it allows easy customization of logging via config files.

Update server logging to use serilog

---

src/Randomizer.App/Randomizer.App.csproj
src/Randomizer.CrossPlatform/Randomizer.CrossPlatform.csproj
src/Randomizer.CrossPlatform/Services/TrackerMapWindowService.cs
src/Randomizer.CrossPlatform/Services/TrackerWindowService.cs

Stream fixes

---

src/TrackerCouncil.Smz3.Data/Configuration/ConfigFiles/ResponseConfig.cs
src/TrackerCouncil.Smz3.Tracking/Services/ICommunicator.cs
src/TrackerCouncil.Smz3.Tracking/Services/SpeakCompletedEventArgs.cs
src/TrackerCouncil.Smz3.Tracking/Services/TextToSpeechCommunicator.cs
src/TrackerCouncil.Smz3.Tracking/Tracker.cs
src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj
src/TrackerCouncil.Smz3.UI/ViewModels/ViewModelBase.cs

Queue item tracking messages & sass around talking a long time

---

src/TrackerCouncil.Smz3.Data/Services/GitHubSpriteDownloaderService.cs
src/TrackerCouncil.Smz3.Data/Services/IGitHubSpriteDownloaderService.cs
src/TrackerCouncil.Smz3.Data/Services/SpriteDownloadUpdateEventArgs.cs
src/TrackerCouncil.Smz3.UI/ServiceCollectionExtensions.cs
src/TrackerCouncil.Smz3.UI/Services/SpriteDownloadWindowService.cs
src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj
src/TrackerCouncil.Smz3.UI/ViewModels/SpriteDownloadWindowViewModel.cs
src/TrackerCouncil.Smz3.UI/Views/SpriteDownloadWindow.axaml
src/TrackerCouncil.Smz3.UI/Views/SpriteDownloadWindow.axaml.cs

Add sprite download progress bar and cancellation

---

src/TrackerCouncil.Smz3.UI/Services/MainWindowService.cs
src/TrackerCouncil.Smz3.UI/Views/MainWindow.axaml.cs

- Update to download sprites after the initial setup
- Prevent downloading sprites unnecessarily when debugging

Sprite download updates

---

src/TrackerCouncil.Smz3.Tracking/TrackerCouncil.Smz3.Tracking.csproj
src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj

Ignore the shitty waffling around of version numbers for the MSU Randomizer. I made a fatal flaw of the UI nuget package is linked to the actual app version. lol

Update MSU Randomizer Version

---

src/TrackerCouncil.Smz3.Chat.Twitch/Models/TwitchPoll.cs
src/TrackerCouncil.Smz3.Data/Configuration/ConfigServiceCollectionExtensions.cs
src/TrackerCouncil.Smz3.Tracking/VoiceCommands/MsuModule.cs
src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj

Also fixes the twitch cancelled poll responses

Fix MSU messages

---

src/TrackerCouncil.Smz3.Abstractions/IGameService.cs
src/TrackerCouncil.Smz3.Tracking/AutoTracking/GameService.cs
src/TrackerCouncil.Smz3.Tracking/VoiceCommands/CheatsModule.cs

Shout-out to that leftover debug routine in the ROM that does the same thing, for showing me what RAM addresses to set!

#564: Added cheat for charging a spineshark

---

src/TrackerCouncil.Smz3.Abstractions/TrackerBase.cs
src/TrackerCouncil.Smz3.Data/Tracking/ViewedObject.cs
src/TrackerCouncil.Smz3.Tracking/AutoTracking/ZeldaStateChecks/ViewedText.cs
src/TrackerCouncil.Smz3.Tracking/Tracker.cs
src/TrackerCouncil.Smz3.Tracking/VoiceCommands/HintTileModule.cs
src/TrackerCouncil.Smz3.Tracking/VoiceCommands/LocationTrackingModule.cs

Basically people seemed to always accidentally mix up the commands for peeking item locations and viewing hint tiles, so I merged the two into a single command.

Merge viewed objects

---

src/TrackerCouncil.Smz3.UI/Services/MainWindowService.cs

Fix disable in update banner not working

---

src/TrackerCouncil.Smz3.Tracking/TrackerCouncil.Smz3.Tracking.csproj
src/TrackerCouncil.Smz3.Tracking/TrackerServiceCollectionExtensions.cs
src/TrackerCouncil.Smz3.UI/App.axaml.cs
src/TrackerCouncil.Smz3.UI/ServiceCollectionExtensions.cs

Fix push-to-talk

---

src/TrackerCouncil.Smz3.Data/Configuration/ConfigFiles/ItemConfig.cs
src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/LightWorld/LightWorldNorthWest.cs
src/TrackerCouncil.Smz3.Tools/Program.cs
src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj
tests/TrackerCouncil.Smz3.Tests/LogicTests/RandomizerTests.cs

skennedy requested the setting spazer as multi for... reasons.

Make spazer as multiple and remove ped/aga ledge weighting

---

src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/ChatConfig.cs
src/TrackerCouncil.Smz3.Tracking/VoiceCommands/ChatIntegrationModule.cs

Another simple change that I hope is worth it. I don't really want to single out users but considering how much Dubz has done for Tracker, I felt like this one was maybe worth doing.

Say something when Dr_Dubz posts art

---

src/TrackerCouncil.Smz3.SeedGenerator/Generation/GameHintService.cs

I really seemed to have forgotten how to spell that day.

Fix issue with the Crateria boss keycard hints

---

src/TrackerCouncil.Smz3.Tracking/VoiceCommands/MsuModule.cs

Fix MSU tracking  for pre-generated MSUs

---

src/TrackerCouncil.Smz3.Tracking/Services/TextToSpeechCommunicator.cs

Fix undoing tracker muting herself not working

---

src/TrackerCouncil.Smz3.Data.SchemaGenerator/Program.cs
src/TrackerCouncil.Smz3.Data.SchemaGenerator/TrackerCouncil.Smz3.Data.SchemaGenerator.csproj
src/TrackerCouncil.Smz3.Data/Configuration/ConfigProvider.cs
src/TrackerCouncil.Smz3.Data/Logic/LogicConfig.cs
src/TrackerCouncil.Smz3.Data/Options/PlandoConfig.cs
src/TrackerCouncil.Smz3.Data/Options/PlandoTextConfig.cs
src/TrackerCouncil.Smz3.Data/Options/Sprite.cs
src/TrackerCouncil.Smz3.Data/RandomizerDirectories.cs
src/TrackerCouncil.Smz3.PatchBuilder/PatchBuilderService.cs
src/TrackerCouncil.Smz3.SeedGenerator/FileData/IpsPatches/IpsPatch.cs
src/TrackerCouncil.Smz3.SeedGenerator/FileData/Patches/FairyPondTradePatch.cs
src/TrackerCouncil.Smz3.SeedGenerator/Generation/RomTextService.cs

Update plando config

---

src/TrackerCouncil.Smz3.SeedGenerator/Generation/GameHintService.cs

Fix tracker incorrectly classifying items in dungeons for hints

---

src/TrackerCouncil.Smz3.Data/WorldData/Regions/SuperMetroid/Crateria/CentralCrateria.cs

Fix bomb toziro logic not requiring morph with hard wall jumps

---

src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/TrackerMapSMDoor.cs
src/TrackerCouncil.Smz3.Data/Options/Config.cs
src/TrackerCouncil.Smz3.Data/Options/PlandoConfig.cs
src/TrackerCouncil.Smz3.Data/Options/RandomizerOptions.cs
src/TrackerCouncil.Smz3.Data/Options/SeedOptions.cs
src/TrackerCouncil.Smz3.Data/ParsedRom/ParsedRomDetails.cs
src/TrackerCouncil.Smz3.Data/Services/GenerationSettingsWindowService.cs
src/TrackerCouncil.Smz3.Data/ViewModels/GenerationWindowGameSettingsViewModel.cs
src/TrackerCouncil.Smz3.Data/maps.json
src/TrackerCouncil.Smz3.SeedGenerator/FileData/Patches/MetroidKeysanityPatch.cs
src/TrackerCouncil.Smz3.SeedGenerator/Generation/RomGenerationService.cs
src/TrackerCouncil.Smz3.SeedGenerator/Generation/RomTextService.cs
src/TrackerCouncil.Smz3.SeedGenerator/Generation/Smz3RomParser.cs
src/TrackerCouncil.Smz3.UI/Services/TrackerMapWindowService.cs
src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj

Add option to not require the crateria boss keycard for Tourian

---

src/TrackerCouncil.Smz3.Tracking/AutoTracking/AutoTrackerModules/ZeldaMiscData.cs
src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj

Fix castle tower not automatically tracking

---

src/TrackerCouncil.Smz3.UI/Views/GenerationSettingsWindow.axaml
src/TrackerCouncil.Smz3.UI/Views/GenerationSettingsWindow.axaml.cs

Fix generation window on smaller displays

---

src/TrackerCouncil.Smz3.Data/Options/Config.cs
src/TrackerCouncil.Smz3.SeedGenerator/FileData/Patches/EtecoonsJinglePatch.cs

Includes #710 ideas as well as Kings Quest V Town Theme, Sonic 2 Special Stage, Manbo's Mambo (Link's Awakening), Saria's Song (Ocarina of Time)

More Etecoons jingles

---

src/TrackerCouncil.Smz3.Data/Options/Config.cs
src/TrackerCouncil.Smz3.SeedGenerator/FileData/Patches/EtecoonsJinglePatch.cs

This should be the last batch, as I'm fresh out of ideas. Please feel free to discard, revise, etc. I can also send clips of how these sound in action.
Added:
Battletoads: Victory/Stage Clear
Castlevania: Vampire Killer
Kirby: Fanfare (two versions - the "buffed" one is pitched lower)
Mega Man series: the classic Boss Selected track
Metal Gear Solid: Game Over
Pizza Tower: It's Pizza Time!
Super Metroid: the other main theme to the game, from the prologue/ending

Even more Etecoons jingles
