- src/Randomizer.SMZ3.Tracking/Configuration/ItemData.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/tracker.json
Added the ability to configure item-specific responses using a _WhenTracked_ property on each item in `tracker.json`.
It is a dictionary where each key is an int that represents the current tracking state. When tracking an item, it tries to find the closest key in the dictionary that is smaller. For example, in a dictionary that has entries for 1, 2 and 5, requesting 4 will return the entry for 2.
If `null` is encountered, it will default to generic item responses. You can use this to add responses for a specific stage or item count, but leave everything else the same. For example, in a dictionary that has an entry for 3 and a `null` entry for 4, requesting 5 will return `null`.
> Added item-specific responses

- src/Randomizer.SMZ3.Tracking/Configuration/TrackerConfig.cs
Despite not being marked as nullable, JsonSerializer will still inject `null` without any warning or error. Now, it'll create a default instance for any missing parts, or throw if the items are missing (as those are pretty critical).
> Fixed crash when using tracker.json from older version

- src/Randomizer.App/Windows/TrackerWindow.xaml.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
I had noticed both personally and from betus's streams that tracker was sometimes pretty slow when tracking things, especially when doing larger things such as clearing large locations. When poking around I noticed each time the progression objects are retrieved for the location list and the map, it was being re-instantiated each time and repopulated for every single location in both spots. This change is to basically cache the progression and only reset it when items are tracked or untracked. While an extreme example, this has changed clearing Ganon's Tower being cleared on the map from around like 5 seconds to 1 second for me.
> Caching progression objects to avoid constant reinstantiation

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
Fixed an issue where asking for a progression hint would cause Tracker to constantly point to Hyrule Castle. It's likely giving a hint for early progression missiles, but since "_track missiles from Hyrule Castle_" doesn't clear something if there's more than one, it would still be considered "untracked".
I added a condition to make sure the item in question hasn't already been tracked (regardless of whether or not the location itself was cleared or not.)
> "Give me a hint" fix

- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/ItemTrackingModule.cs
Added the ability to track everything in an area, including out of logic items, by saying e.g. "_Hey tracker, force track everything in Tower of Hera_" or "_Hey tracker, I cheated my way into Tower of Hera_".
I still haven't figured out how to make "clear dungeon" work more accurately. I might just need to rewrite it or something.
> Track all out of logic items

- src/Randomizer.App/RomGenerator.cs
- src/Randomizer.App/ViewModels/RandomizerOptions.cs
- src/Randomizer.App/ViewModels/SeedOptions.cs
- src/Randomizer.App/Windows/GenerateRomWindow.xaml
- src/Randomizer.App/Windows/GenerateRomWindow.xaml.cs
- src/Randomizer.App/Windows/RomListWindow.xaml
- src/Randomizer.App/Windows/RomListWindow.xaml.cs
- src/Randomizer.SMZ3.Tracking/TrackerState.cs
- src/Randomizer.SMZ3/Config.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
- src/Randomizer.SMZ3/Playthrough.cs
- src/Randomizer.SMZ3/RandomizerGenerationException.cs
- src/Randomizer.SMZ3/StandardFiller.cs
- src/Randomizer.Shared/Enums/ItemCategory.cs
- src/Randomizer.Shared/Enums/ItemType.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/RandomizerTests.cs
Adding the ability to have more granular control over what gets generated where and adding the ability to share configs, opening the possibility for community created seeds for streamers to play.
- Every location can now have either progression items, junk items, or specific items be specified
- All progression items can be specified as early items
- Updated rom generation to handle potentially unwinnable seeds gracefully by displaying an error message upon generating the rom
- Depending on settings, sometimes you can try regenerating the seed when this error displays, and it'll work successfully. If you requested a particular item at a location where the item isn't needed to get there, it may have randomly picked a logic chain that is impossible.
- Base 64 encoded settings strings can be …
> Community seeds

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.SMZ3/ILogic.cs
- src/Randomizer.SMZ3/Logic.cs
- src/Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/GreenBrinstar.cs
- src/Randomizer.SMZ3/Regions/SuperMetroid/Norfair/UpperNorfairWest.cs
- src/Randomizer.SMZ3/Regions/Zelda/EasternPalace.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/DeathMountain/LightWorldDeathMountainWest.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/LightWorldNorthEast.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/LightWorldSouth.cs
- src/Randomizer.SMZ3/Regions/Zelda/MiseryMire.cs
- src/Randomizer.SMZ3/Regions/Zelda/PalaceOfDarkness.cs
- src/Randomizer.SMZ3/Regions/Zelda/TurtleRock.cs
- src/Randomizer.Shared/Models/LogicConfig.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/LogicConfigTests.cs
Added a few simple to implement tricks
- Mockball
- Sword Only Dark Rooms
- Light World South Fake Flippers
> Adding Additional Tricks

- src/Randomizer.App/RomGenerator.cs
- src/Randomizer.App/Windows/GenerateRomWindow.xaml.cs
- src/Randomizer.App/Windows/RomListWindow.xaml.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
- src/Randomizer.Shared/Enums/ItemCategory.cs
- src/Randomizer.Shared/Enums/ItemType.cs
- src/Randomizer.Shared/Enums/ItemTypeExtensions.cs
Fixes to prevent issues with playing seeds that don't match the requested settings like in Pink's stream.
- After generating a seed, it will now throw an error popup if it doesn't match the user settings
- Spazer and tunics no longer show up as potential early items as they are not technically progression items
> Catch Seeds that are Inconsistent With Requested Settings

- src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/TrackerOptions.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/TrackerModule.cs
- src/Randomizer.SMZ3.Tracking/tracker.json
Pink inspired me by sometimes tracking multiple items in rapid succession — issues commands while Tracker is still responding to the previous command. I figured it'd be fun to add a little flair by having Tracker interrupt these kinds of situations with some sass.
Considerations:
- How many times should Tracker tolerate being interrupted before speaking up about it?
- Should we add a timeout before speaking up again, in addition to the threshold?
- It's not likely to happen too often. And if it does happen often, we should increase the threshold instead. But still, it's worth considering.
- I've added #97 so for similar ideas in the future, we can experiment more easily and give users the ability to toggle something off.
> [Experimental] Handle interruptions

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/TrackerOptions.cs
- src/Randomizer.SMZ3.Tracking/tracker.json
I'm not entirely sure what happened in Pink's stream, but I'm adding more sass and letting tracker 'break' when it's happened too many times, at which point she doesn't repeat what she was saying, which hopefully fixes it.
https://clips.twitch.tv/CallousTubularPeppermintTBTacoLeft-H8a2UZQUxYA3V3jz
> Attempt to fix interruptions by adding more sass

- src/Randomizer.SMZ3.Tracking/Configuration/HintsConfig.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ItemData.cs
- src/Randomizer.SMZ3.Tracking/Configuration/SpoilerConfig.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/TrackerModule.cs
- src/Randomizer.SMZ3.Tracking/tracker.json
Works for both regions, dungeons, and rooms.
If spoilers are enabled, Tracker will straight up list all the items there.
If hints are enabled, she'll tell you whether there's anything useful or not. 
I kinda went all in and considered whether pendants are useful, for which I had to create some code to consider some item chains. It would be a lot of work to apply this to everything we've already done, but might be worth adding once it's noticed.
> Added "Hey tracker, what's in <area>?"

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.App/ViewModels/GeneralOptions.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ItemData.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ResponseConfig.cs
- src/Randomizer.SMZ3.Tracking/Configuration/SpoilerConfig.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/TrackerModule.cs
- src/Randomizer.SMZ3.Tracking/tracker.json
- **Removed interruptions**
It was funny for a little bit but didn't turn out the way I wanted, and at this stage it's not worth trying to get it to work well
- Fixed bullshit being considered progression
- Fixed an error when asking for hints about an item that can't be found (anymore)
- Fixed chat integration not working when entering a channel URL instead of just the username in the **Twitch Channel** field
- Improved username pronunciation by treating underscores as spaces
- Fixed "_You need the Fire Rod before you can get the Fire Rod_" hints
This PR will update the version to 4.2.2.
> Bug fixes and polish

- src/Randomizer.App/App.xaml.cs
- src/Randomizer.App/ViewModels/GeneralOptions.cs
- src/Randomizer.App/Windows/OptionsWindow.xaml
- src/Randomizer.App/Windows/OptionsWindow.xaml.cs
- src/Randomizer.App/Windows/TrackerWindow.xaml.cs
- src/Randomizer.SMZ3.ChatIntegration/IChatApi.cs
- src/Randomizer.SMZ3.ChatIntegration/IChatAuthenticationService.cs
- src/Randomizer.SMZ3.ChatIntegration/IChatClient.cs
- src/Randomizer.SMZ3.ChatIntegration/MessageReceivedEventArgs.cs
- src/Randomizer.SMZ3.ChatIntegration/Models/AuthenticatedUserData.cs
- src/Randomizer.SMZ3.ChatIntegration/Models/ChatMessage.cs
- src/Randomizer.SMZ3.ChatIntegration/Models/ChatPoll.cs
- src/Randomizer.SMZ3.ChatIntegration/Models/ChatUserData.cs
- src/Randomizer.SMZ3.ChatIntegration/OAuthChatAuthenticationService.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ChatConfig.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/TrackerOptions.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/ItemTrackingModule.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/TrackerModule.cs
- src/Randomizer.SMZ3.Tracking/tracker.json
- src/Randomizer.SMZ3.Twitch/Models/TwitchPoll.cs
- src/Randomizer.SMZ3.Twitch/Models/TwitchPollChoice.cs
- src/Randomizer.SMZ3.Twitch/Models/TwitchUser.cs
- src/Randomizer.SMZ3.Twitch/TwitchAuthenticationService.cs
- src/Randomizer.SMZ3.Twitch/TwitchChatAPI.cs
- src/Randomizer.SMZ3.Twitch/TwitchChatClient.cs
- src/Randomizer.SMZ3.Twitch/TwitchChatMessage.cs
In this I have created a Twitch API class which can be used to making calls out to the Twitch API for integration that the current Twitch client does not currently provide. Currently this is used by our internal TwitchChatClient for poll creation. I opted to include all of this in the TwitchChatClient just in the case that the client we're currently using adds poll functionality. I figured one sort of front facing client to use in the application would be easier than multiple.
To test this functionality, I made use of the Twitch CLI's mock api functionality. However, there are a few unfortunate holes in its implementation:
- The authentication endpoint fails to work if you provide the scopes chat:read chat:edit. However, it does work with just channel:read:polls channel:manage:polls
- …
> Implementing Twitch Polls

- src/Randomizer.SMZ3.ChatIntegration/IChatApi.cs
- src/Randomizer.SMZ3.ChatIntegration/Models/TwitchAPIResponse.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
- src/Randomizer.SMZ3.Twitch/Models/TwitchPoll.cs
- src/Randomizer.SMZ3.Twitch/Models/TwitchUser.cs
- src/Randomizer.SMZ3.Twitch/TwitchChatAPI.cs
- src/Randomizer.SMZ3.Twitch/TwitchChatClient.cs
Trying not to lump literally everything into one massive PR this time to make them easier to review.
This resolves an issue I accidentally introduced with Twitch polls. My ambiguity on some variable names bit me a bit (I used IsSuccessful for if the poll was completed successfully, not for if the request was completed). Now all Twitch API requests need to extend a TwitchAPIResponse class that has an IsSuccessful response for if the api call was successful or not. I've renamed the poll successful variables to remove any ambiguity.
> Fix for not detecting when polls are opened

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/EmulatorAction.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/IEmulatorConnector.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/LuaConnector.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/USB2SNESConnector.cs
- src/Randomizer.SMZ3.Tracking/tracker.json
- src/Randomizer.SMZ3/Regions/Zelda/DarkWorld/DarkWorldNorthEast.cs
- src/Randomizer.SMZ3/Regions/Zelda/DarkWorld/DarkWorldNorthWest.cs
- src/Randomizer.SMZ3/Regions/Zelda/DarkWorld/DarkWorldSouth.cs
- src/Randomizer.SMZ3/Regions/Zelda/HyruleCastle.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/DeathMountain/LightWorldDeathMountainEast.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/DeathMountain/LightWorldDeathMountainWest.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/LightWorldNorthEast.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/LightWorldNorthWest.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/LightWorldSouth.cs
- src/Randomizer.Shared/Enums/LocationMemoryType.cs
Unfortunately, betus ran into some issues with auto tracking being pretty slow (sometimes taking like 30 seconds to track stuff), and even more unfortunate is that I can't reproduce the issue. DigitalBasic and Pink haven't had any issues either. This eventually seemed to culminate in the auto tracker tracking a series of locations for betus that always seem to give me problems. 🙃 
However, I do have some theories. I changed the rate of sending requests to the emulator for memory from 0.25 seconds to 0.1 seconds between last week and this week. And while the USB2SNES connection will only have one request out there at a time due to the USB2SNES limitation of not returning any sort of identifiable information in the response, the Lua connection will send out messages to the emulator …
> Hopefully fixing issues with slowdown and tracking incorrect items

- src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTrackerZeldaState.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/FallFromMoldorm.cs
- src/Randomizer.SMZ3/Regions/Zelda/CastleTower.cs
- src/Randomizer.SMZ3/Regions/Zelda/DesertPalace.cs
- src/Randomizer.SMZ3/Regions/Zelda/EasternPalace.cs
- src/Randomizer.SMZ3/Regions/Zelda/HyruleCastle.cs
- src/Randomizer.SMZ3/Regions/Zelda/IcePalace.cs
- src/Randomizer.SMZ3/Regions/Zelda/LightWorld/LightWorldNorthWest.cs
- src/Randomizer.SMZ3/Regions/Zelda/MiseryMire.cs
- src/Randomizer.SMZ3/Regions/Zelda/PalaceOfDarkness.cs
- src/Randomizer.SMZ3/Regions/Zelda/SkullWoods.cs
- src/Randomizer.SMZ3/Regions/Zelda/SwampPalace.cs
- src/Randomizer.SMZ3/Regions/Zelda/ThievesTown.cs
- src/Randomizer.SMZ3/Regions/Zelda/TowerOfHera.cs
- src/Randomizer.SMZ3/Regions/Zelda/TurtleRock.cs
skelebro had an issue with auto tracker thinking that he entered GT when he entered the mimic cave. Looked back at the memory documentation, and dungeon rooms and overworld screens are still in two bytes rather than one, and it happened that the GT entrance and mimic care share the same first byte. I went through and looked at all of the other entrances and trick room numbers, and that was the only one I found.
Along with these changes, I went ahead and added some of the extra entrances for some of the dungeons where you can leave and come back (desert, turtle rock, etc.). Also converted them to regular integers since that's what's printed in the logs. Not sure why I did that originally since I had to find them all through walking around and looking at the logs. lol
Also went and added …
> Update rooms and screens to uint16 instead of uint8

- src/Randomizer.App/TrackerLocationSyncer.cs
- src/Randomizer.App/Windows/TrackerWindow.xaml.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
- src/Randomizer.SMZ3/Regions/Zelda/SkullWoods.cs
Closing #144
- Pulled the race/keysanity setting from the generated rom rather than current settings
- Disabling hints/spoilers for races
- Removed corrections when hints/spoilers are disabled
- Removed dungeon boss item tracking when spoilers aren't enabled
Also updating it to no longer spoil medallion rewards when you haven't peeked the dungeons and no longer show certain locations until you collect dungeon rewards since that was brought up during and after the race. I'm not really super fond of having them in the TrackerLocationSyncer, but they're a pretty odd assortment of checks that I'm not sure if they should have anything fancy for them. But, if you have some better place to put the logic you'd prefer, let me know.
> Race fixes

- src/Randomizer.App/TrackerLocationSyncer.cs
- src/Randomizer.App/ViewModels/TrackerMapLocationViewModel.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/EnteredDungeon.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/ViewedMap.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
This resolves various fixes for keysanity mode that came up during Pink's playthrough. No tracker window updates as of yet. I'd need to look into exactly how it works first. But, this should at least get location tracking working properly. I feel like people are more likely to use autotracking with keysanity mode anyway just because of the sheer annoyance of keeping track of all the keys.
Issues resolved
- Forced the map to not assume keys for keysanity rather than the one that assumes keys as it'll show what's actually in logic. The location list should work the same as before though.
- The "take a look at this" should now require the map for keysanity to avoid spoiling locations.
- All locations in dungeons should now be counted as treasure for keysanity mode.
- Fixed non green pendant …
> Keysanity Fixes

- src/Randomizer.App/RomGenerator.cs
- src/Randomizer.App/ViewModels/RandomizerOptions.cs
- src/Randomizer.App/ViewModels/SeedOptions.cs
- src/Randomizer.App/Windows/GenerateRomWindow.xaml
- src/Randomizer.App/Windows/GenerateRomWindow.xaml.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
- src/Randomizer.SMZ3/Config.cs
Some folks wanted additional options to disable hints/spoilers piecemeal without enabling the race option and disabling everything.
I also updated it so that when the race mode is enabled or the option to disable spoiler log is enabled, it actually fully disables location printing in the spoiler log.
> Additional Race Options

- src/Randomizer.SMZ3.Tracking/Configuration/ConfigFiles/RegionConfig.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ConfigFiles/ResponseConfig.cs
- src/Randomizer.SMZ3.Tracking/Configuration/Yaml/Sassy/requests.yml
- src/Randomizer.SMZ3.Tracking/Configuration/Yaml/Sassy/responses.yml
- src/Randomizer.SMZ3.Tracking/Configuration/Yaml/Templates/responses.yml
- src/Randomizer.SMZ3.Tracking/Tracker.cs
Adds a chance for Tracker to say "Is this even randomized?" when marking or tracking an item at its vanilla location.
I also added map names to the Region config. I don't know whether you forgot these or something else was missing on my end, but auto-tracking stopped updating the map. I fixed a crash as a result from this in my last PR, but now I found the root case (I guess).
> Vanilla item response + auto-tracker map fix

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.App/Windows/OptionsWindow.xaml.cs
- src/Randomizer.SMZ3.Tracking/Configuration/TrackerConfigProvider.cs
- src/Randomizer.SMZ3.Tracking/Services/UIService.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/TrackerModule.cs
- src/Randomizer.SMZ3/Generation/PlandoConfig.cs
So the seed I rolled to test out the GT item counting literally only had keys, the map, and compass before the big key. This was kind of nagging me a bit, so I decided to check it out, and sure enough tracker was still going into the whole "You got another X item. Y treasures left." before which I think gets in the way of counting. This fixes that.
While doing that, I also found the spot that was causing the issue where Tracker wouldn't announce that there are no remaining items left when using the auto tracking, so I'm fixing that as well.
> GT Item and Treasure Count Fixes

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.App/TrackerLocationSyncer.cs
- src/Randomizer.App/ViewModels/RandomizerOptions.cs
- src/Randomizer.App/ViewModels/TrackerMapLocationViewModel.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/LuaConnector.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ConfigFiles/LocationConfig.cs
- src/Randomizer.SMZ3.Tracking/Configuration/ConfigTypes/BasicVoiceRequest.cs
- src/Randomizer.SMZ3.Tracking/TrackerLogic.cs
- src/Randomizer.SMZ3/Location.cs
- src/Randomizer.SMZ3/Logic.cs
- src/Randomizer.SMZ3/Regions/SuperMetroid/Maridia/InnerMaridia.cs
- src/Randomizer.Shared/Models/LogicConfig.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/LogicConfigTests.cs
Wasn't intending to make as many updates as this, but was watching Digi play and a few things came up that this PR resolves, along a couple items that came up with the async seed.
- Game mode/item placement was not being copied in with settings strings
- BasicVoiceRequests weren't merging properly if cases were different
- With the walljump patch, hi jump is no longer needed for the left sand pit, so I removed it
- Dungeon bosses were showing up as accessible even if you didn't have the means to get to them
- The watering hole and that hidden room to the top left of Maridia were in logic in medium wall jump without space jump, speed booster, or grapple which should be needed to pass the large room
- Backed out PR 213 as it prevented you from closing and reopening tracker, but I'm no …
> Updates from Digi's Stream and Async Race

- src/Randomizer.App/RomGenerator.cs
- src/Randomizer.Data/Options/Config.cs
- src/Randomizer.Data/Services/IMetadataService.cs
- src/Randomizer.Data/Services/ITrackerStateService.cs
- src/Randomizer.Data/Services/MetadataService.cs
- src/Randomizer.Data/Services/TrackerStateService.cs
- src/Randomizer.Data/WorldData/World.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3/Contracts/IGameHintService.cs
- src/Randomizer.SMZ3/Contracts/ISeededRandomizer.cs
- src/Randomizer.SMZ3/FileData/Patcher.cs
- src/Randomizer.SMZ3/Generation/GameHintService.cs
- src/Randomizer.SMZ3/Generation/SeedData.cs
- src/Randomizer.SMZ3/Generation/Smz3Plandomizer.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
- src/Randomizer.SMZ3/Generation/StandardFiller.cs
- src/Randomizer.Shared/Migrations/20221016050403_Multiworld.Designer.cs
- src/Randomizer.Shared/Migrations/20221016050403_Multiworld.cs
- src/Randomizer.Shared/Models/TrackerBossState.cs
- src/Randomizer.Shared/Models/TrackerDungeonState.cs
- src/Randomizer.Shared/Models/TrackerItemState.cs
- src/Randomizer.Shared/Models/TrackerLocationState.cs
- src/Randomizer.Shared/Models/TrackerState.cs
Closes #230 
Here's a summary of the main changes in the PR
- The spoiler log was updated to print off info for all worlds. I also updated it to include hints.
- The standard filler now looks at the individual world configs for settings like item placement.
- The SMZ3Randomizer now supports taking in multiple configs and generating the worlds based on those configs.
- Updates to in game hint generation to work with multiple worlds.
- Updated the database to house multiple worlds, and all data is saved to the db 
My general thought is going forward tracker will load all of the world from the db. Currently when you start the tracker, it actually generates a world and then overrides everything. I'll probably create a "TrackerFiller" or something to use instead of the Standard or Plando …
> Multiworld Generation

- src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTrackerMetroidState.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/EmulatorAction.cs
There have been a few issues where if auto tracker is connected before the game fully loads, it'll track the SM bosses and locations. This change looks for a valid game state before tracking. It also resets everything on disconnects.
> Fixes issues with items being tracked on reset

- src/Randomizer.SMZ3/Playthrough.cs
Fixes #281
Hint tile generation would be messed up if locations in a sphere only opened up the ability to defeat a boss that would open additional locations, such as Phantoon and Kraid.
> Hint Tile Fix

- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
- src/Randomizer.Shared/Enums/ItemType.cs
Apparently tracker wasn't doing the IsWorth check for stuff like mushrooms for location hints. Also added bottles -> sick kid, but added where it won't say it's worth it if you already have a bottle.
Fixes #288
> Fix tracker counting mushroom/magic powder as junk

- src/Randomizer.Data/Configuration/ConfigFiles/ItemConfig.cs
Added the new "It goes on your extremities" hint to a couple items so Gloves isn't left with only one hint.
I'm iffy on adding this hint for shields, because it could mislead people into going out of their way to get it, which would be 1) annoying, but also 2) very funny.
> Replaced Gloves hint that sent PKR down the wrong path

- src/Randomizer.Data/Configuration/ConfigTypes/ItemData.cs
- src/Randomizer.Data/Options/ItemSettingOptions.yml
- src/Randomizer.Data/Services/TrackerStateService.cs
- src/Randomizer.Multiplayer.Client/MultiplayerClientService.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/MultiplayerModule.cs
- src/Randomizer.SMZ3/Generation/Smz3GeneratedRomLoader.cs
- Fix for items not being in the UI when there are no instances of it in the current player's world
- Fixed a couple item setting options
- Update to make sure that a player is actually in game before giving out items
- Only mark the player as beating both final bosses when one of the two was actually detected
Closes #317
> Multiworld Bug Fixes

- src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
This preserves capitalization and improves a few pronunciations, without the slower reading the TTS gives it when we also insert spaces.
> Use sender's display name in greetings

- src/Randomizer.Data/Logic/ILogic.cs
- src/Randomizer.Data/Logic/Logic.cs
- src/Randomizer.Data/Logic/LogicConfig.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Crateria/EastCrateria.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/WreckedShip.cs
This does actually change default behavior with new seeds, but because this feels pretty similar to the Parlor Speed Boost that was added a long time ago both in terms of execution difficulty and type, I thought it would be appropriate in the tricks section.
> Adding Moat Speed Booster Trick

- src/Randomizer.SMZ3.Tracking/VoiceCommands/LocationTrackingModule.cs
Closes #329.
Rooms and regions can now be force-cleared! Checked into what happens when force clearing a dungeon vs. regularly clearing it and there's no code that would make a distinction; it always acts like a force-clear.
> Listen for "force/sudo clear" on rooms, regions, and dungeons, too.

- src/Randomizer.App/Windows/GenerateRomWindow.xaml.cs
- src/Randomizer.Data/Services/IMetadataService.cs
- src/Randomizer.Data/Services/MetadataService.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/BlueBrinstar.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/GreenBrinstar.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/KraidsLair.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/PinkBrinstar.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Brinstar/RedBrinstar.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Crateria/CentralCrateria.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Crateria/EastCrateria.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Crateria/WestCrateria.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Maridia/InnerMaridia.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Maridia/OuterMaridia.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/LowerNorfairEast.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/LowerNorfairWest.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/UpperNorfairCrocomire.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/UpperNorfairEast.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/UpperNorfairWest.cs
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/WreckedShip.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3/Generation/GameHintService.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/LocationLogicTests.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/LogicConfigTests.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/RandomizerTests.cs
Closes #14. I don't know if we want to try to squeeze this into this week's release or give it a little more time to bake, but here's the PR. I tried not to mess too much with existing logic or property names, except when the location had the same name as the room it went into and the compiler didn't like that. Asking for hints and clearing locations seemed to be working well. I did have to add a workaround so rooms not declared in `rooms.yml` wouldn't cause problems; I don't know if we want something more robust in place there.
Room names are from this wiki: https://wiki.supermetroid.run/List_of_rooms
Also closes #327, by way of giving the room with the Plasma Beam the name "Plasma Beam Room".
> Move every Metroid Location into a Room

- src/Randomizer.SMZ3/Generation/GameHintService.cs
This resolves an issue brought up by ProfHammerRadd. Basically if GT has a smaller crystal count than Ganon, then it could think that a seed is beatable sooner than it could be because it was just looking for if the moldorm chest and not give the proper hint.
This change will make it so that hint tiles will make sure you can access the number of crystals you need (max between GT and Ganon).
> Update Hints to Require Crystal Dungeons

- src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/EmulatorAction.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/EmulatorMemoryData.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/GameService.cs
1. This adds in a check where it pulls in the items gifted to the player, the ones that should have been sent to the player, and compares them. If any items were missed, it'll resend them.
- I updated the GameService to use BitConverter and match some more C# stylings.
1. Reads have to happen sequentially, and the above added another read. I've been a bit worried about extra reads causing slowdown and making some things less stable. Due to this, I added in functionality to have reads have an optional frequency. I moved item and boss checks to 1 second because they don't really need to be happening multiple times a second.
> Resend Missed Multiworld Items

- setup/randomizer.app.iss
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.Multiplayer.Server/MultiplayerDbService.cs
- src/Randomizer.Multiplayer.Server/Randomizer.Multiplayer.Server.csproj
- src/Randomizer.SMZ3.Tracking/AutoTracking/GameService.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/MetroidStateChecks/MetroidDeath.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/ZeldaDeath.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/MultiplayerModule.cs
- Prevent tracker remarking on deaths when killed by the game service
- Prevent death linked players from tracking deaths to the server
- Fixed server logging that was broken
> Multiworld Fixes

- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.App/Windows/RomListWindow.xaml.cs
Fixes a few things
1. The options window would not actually create the output directory, meaning if someone closed and reopened before generating a rom it would ask to update settings again
2. It never validated the options when closing the options window, so people wouldn't know if they missed required fields
3. It would never show the rom list/generate button after updating the options initially, meaning people would be stuck in a loop unless they selected a, output folder that already exists
> Init settings bug fix

- src/Randomizer.Data/Options/ItemSettingOptions.yml
This is related to #371, but doesn't fully fix it.
Basically, starting with a flute breaks being able to switch to the shovel when you get it. This is probably related to the split shovel/flute items and will need some other memory adjustments that I'll need to figure out. However, when testing, I found that when you activate the flute, it sort of works itself out, so for now I'm updating it to require you to activate the flute if you start with it.
> Temp workaround for starting flutes

- src/Randomizer.App/Windows/OptionsWindow.xaml
- src/Randomizer.App/Windows/TrackerWindow.xaml.cs
- src/Randomizer.Data/Options/GeneralOptions.cs
- src/Randomizer.Data/Options/RandomizerOptions.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/AutoTracker.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/USB2SNESConnector.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/AutoTrackerModule.cs
Updated to be able to specify the IP address to use a non-localhost IP address. Needed for my current funky setup of having SMZ3 in a VM and RetroArch on Linux.
> Allow customizing qusb2snes ip address

- src/Randomizer.SMZ3.Tracking/AutoTracking/GameService.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/MsuModule.cs
I wasn't sure if it made more sense to do the emulator writes in `GameService` or do them straight from `MsuModule`, so I went for `GameService`, but I can move it if I need to, since `MsuModule` also has a `Tracker` property and can get to `AutoTracker` from there. Let me know!
Otherwise, this seems to be working. The only downside is it might unnecessarily cancel resume on the rare occasion a resumable track gets shuffled and winds up as the same track, but I don't think we need to worry about it too much?
Closes #386.
> Cancel MSU resume when tracks shuffle

- CasRandomizer.sln
- src/Randomizer.App/App.xaml.cs
- src/Randomizer.App/Controls/MultiRomListPanel.xaml.cs
- src/Randomizer.App/Controls/RomListPanel.cs
- src/Randomizer.App/Controls/SoloRomListPanel.xaml.cs
- src/Randomizer.App/Windows/GenerateRomWindow.xaml.cs
- src/Randomizer.App/Windows/OptionsWindow.xaml
- src/Randomizer.App/Windows/OptionsWindow.xaml.cs
- src/Randomizer.CrossPlatform/Program.cs
- src/Randomizer.CrossPlatform/Randomizer.CrossPlatform.csproj
- src/Randomizer.CrossPlatform/ServiceCollectionExtensions.cs
- src/Randomizer.CrossPlatform/msu-randomizer-settings.yml
- src/Randomizer.CrossPlatform/msu-randomizer-types.json
- src/Randomizer.Data/Options/GeneralOptions.cs
- src/Randomizer.Data/Options/OptionsFactory.cs
- src/Randomizer.Data/Options/PatchOptions.cs
- src/Randomizer.Data/Options/RandomizerOptions.cs
- src/Randomizer.Data/Options/SeedOptions.cs
- src/Randomizer.Data/Options/Sprite.cs
- src/Randomizer.Data/Randomizer.Data.csproj
- src/Randomizer.Data/Services/GameDbService.cs
- src/Randomizer.Data/Services/IGameDbService.cs
- src/Randomizer.Data/Services/SourceRomValidationService.cs
- src/Randomizer.PatchBuilder/PatchBuilderService.cs
- src/Randomizer.PatchBuilder/Program.cs
- src/Randomizer.PatchBuilder/Randomizer.PatchBuilder.csproj
- src/Randomizer.SMZ3/Generation/RomTextService.cs
- src/Randomizer.Shared/Models/RandomizerContext.cs
- src/Randomizer.Sprites/SpriteService.cs
This is a first implementation of a cross platform randomizer.  Right now it's just a console app that is only capable of generating roms, playing previously generated roms, and deleting roms. This doesn't work with tracking at all yet.
The main summary of changes I implemented are as follows:
1. I created a GameDbService which to use for retrieving generated roms and multiplayer games to be shared between the two
2. Since currently this tool requires you to edit the options manually, I updated the Randomizer Options to work with yaml instead of json. For previous users, it should load the json, but then it will save the yaml after that. I figure in a future version, we can remove the json support.
4. I updated usages of Environment.ExpandEnvironmentVariables to …
> Initial implementation of cross platform randomizer

- src/Randomizer.App/EnumDescriptionBindingSourceExtension.cs
- src/Randomizer.App/EnumDescriptionConverter.cs
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.App/Windows/GenerateRomWindow.xaml
- src/Randomizer.App/Windows/MultiplayerConnectWindow.xaml
- src/Randomizer.App/Windows/OptionsWindow.xaml
- src/Randomizer.App/Windows/SpriteWindow.xaml
- src/Randomizer.Data/Configuration/ConfigTypes/ChatConfig.cs
- src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml
- src/Randomizer.Data/Options/GeneralOptions.cs
- src/Randomizer.Data/Options/TrackerOptions.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/ChatIntegrationModule.cs
- src/Randomizer.Shared/Enums/GanonsTowerGuessingGameStyle.cs
- Requires GT number guesses to be the only part of a message
- Introduces an option for the GT guessing game for winners to be determined by who is the closest without going over
- I also noticed my previous change broke the look of some of the enum dropdowns. (I now remember why I did them the weird way I did before.) I created a new binding source and updated the description field so that the dropdown text can have spaces and whatnot and still work.
> GT Game and Enum Dropdown Updates

- src/Randomizer.Data/Services/TrackerStateService.cs
- src/Randomizer.Data/WorldData/World.cs
- src/Randomizer.SMZ3/Contracts/IGameHintService.cs
- src/Randomizer.SMZ3/FileData/GetPatchesRequest.cs
- src/Randomizer.SMZ3/FileData/Patches/ZeldaTextsPatch.cs
- src/Randomizer.SMZ3/Generation/GameHintService.cs
- src/Randomizer.SMZ3/Generation/RomTextService.cs
- src/Randomizer.SMZ3/Generation/Smz3GeneratedRomLoader.cs
- src/Randomizer.SMZ3/Generation/Smz3MultiplayerRomGenerator.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
- src/Randomizer.SMZ3/Generation/WorldGenerationData.cs
- src/Randomizer.Shared/Enums/HintState.cs
- src/Randomizer.Shared/Enums/HintTileType.cs
- src/Randomizer.Shared/Migrations/20231119163811_SaveHintTiles.Designer.cs
- src/Randomizer.Shared/Migrations/20231119163811_SaveHintTiles.cs
- src/Randomizer.Shared/Models/HintTile.cs
- src/Randomizer.Shared/Models/RandomizerContext.cs
- src/Randomizer.Shared/Models/TrackerHintState.cs
- src/Randomizer.Shared/Models/TrackerState.cs
- src/Randomizer.Shared/Multiplayer/MultiplayerPlayerGenerationData.cs
This change is to change the way hints are generated so that they can be saved to the database. This is being done so tracker can know what hints were generated as well as allow it to remember the state of whether a hint has been viewed or cleared.
I'll make the UI for keeping track of hints and auto detection of reading hints in another PR.
> Save hints to db

- src/Randomizer.Abstractions/TrackerBase.cs
- src/Randomizer.Data/Configuration/ConfigFiles/ResponseConfig.cs
- src/Randomizer.Data/Randomizer.Data.csproj
- src/Randomizer.Data/WorldData/VisibleItemMetroid.cs
- src/Randomizer.Data/WorldData/VisibleItemZelda.cs
- src/Randomizer.Data/WorldData/VisibleItems.cs
- src/Randomizer.Data/WorldData/VisibleItems.yml
- src/Randomizer.SMZ3.Tracking/AutoTracking/MetroidStateChecks/VisibleItemMetroidCheck.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/VisibleItemZeldaCheck.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/LocationTrackingModule.cs
There are definitely some visible items I missed, and there's going to need to be some additional stuff added on the Metroid side. For example, probably no need to mark the old tourian launch pad when you have the speed booster as you're likely rocketing up to get the item. Also probably probably shouldn't mark the post Chozo concert speed booster item unless you've destroyed the egg or whatever it is around the item.
But, this is a start for some of the most common marked locations, and I'll probably add some other basic ones to the list this week. (It just dawned on me I left out the library, for example.)
Closes #275
> Initial auto mark items changes

- src/Randomizer.SMZ3.Tracking/Tracker.cs
Fixes #432 
Also shouldn't cause problems with tracking content as it only looks for valid locations in the history.
> Fix timer reset not working after tracking & undoing

- src/Randomizer.Abstractions/TrackerBase.cs
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.Data/Configuration/ConfigFiles/ResponseConfig.cs
- src/Randomizer.Data/Configuration/Yaml/Sassy/responses.yml
- src/Randomizer.SMZ3.Tracking/Tracker.cs
Just a random idea I've had for a while. Betus can't keep getting away with this.
Or well, I guess he still can. It looks like we only save specific items at locations, but not the other possible options like guaranteeing early boots or something.
> Sass on marking/tracking pre-configured locations

- src/Randomizer.App/Windows/MsuTrackWindow.xaml.cs
- src/Randomizer.Data/Options/MsuTrackDisplayStyle.cs
- src/Randomizer.SMZ3.Tracking/MsuDisplayTextBuilder.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/MsuModule.cs
I really kind of want to see the MSU pack name/author in the on-screen info. I've wanted this for longer, since the track info itself isn't always enough to find out which pack it's from, but now that the bad/weird pack has a YAML, I figured I might as well just make the change myself.
I was about to complicate the MSU track output text function with some sort of "MsuDisplayTextBuilder" class when I realized the MSU rando lib already has a `Track.GetDisplayText(bool)` function that does exactly that. The formatting is slightly different, but I figured that's probably not a huge deal.
If it is, let me know, and I'll overcomplicate things anyway. In case we need more control over the formatting or something.
> Add MSU creator to horizontal MSU display

- docs/ReleaseNotes.md
- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.Data/Options/GeneralOptions.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/ViewedText.cs
- src/Randomizer.SMZ3.Tracking/Services/Speech/NullSpeechRecognitionService.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
Fixes #459
I'll push out a patch release for this once this is merged in since it prevents saving and loading seeds properly.
> Fix loading viewed hint tiles about dungeon requirements

- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.Data/WorldData/Location.cs
- src/Randomizer.SMZ3.Tracking/VoiceCommands/SpoilerModule.cs
- src/Randomizer.SMZ3/Contracts/IGameHintService.cs
- src/Randomizer.SMZ3/Generation/GameHintService.cs
- src/Randomizer.SMZ3/Generation/Smz3MultiplayerRomGenerator.cs
- src/Randomizer.SMZ3/Generation/Smz3Plandomizer.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
- src/Randomizer.SMZ3/Infrastructure/PlaythroughService.cs
- src/Randomizer.SMZ3/Playthrough.cs
- src/Randomizer.SMZ3/RandomizerServiceCollectionExtensions.cs
- src/Randomizer.Tools/Program.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/RandomizerTests.cs
Basically, when asking tracker if there is anything in the crystal dungeon, it was factoring in getting the crystal itself, so crystal dungeons would always say that they are required. Hint tiles avoided this by not giving hints around crystal dungeons unless you're playing keysanity.
For this, when generating the playthrough for tracker hints, she'll basically act like you have the crystal to prevent this from happening. Even if you ask for hints before completing the dungeon, she'll say something like "If it didn't have a crystal, you could skip it." For pendant dungeons, the hints factor in whether you've got the pendant or not, even for downstream locations. So if ped has something, she'll say that the dungeon is required until you beat the dungeon. After that, she'll say that it has …
> Fix crystal dungeon tracker hints

- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.SMZ3.Tracking/AutoTracking/USB2SNESConnector.cs
So recently I figured out that SMZ3 Cas' had an issue with autotracking with QUSB2SNES and the Fx Pak Pro on Linux. Linux + QUSB2SNES + RetroArch works fine. Windows + QUSB2SNES + Fx Pak Pro also work just fine.
Turns out, for whatever reason, for read requests of more than 128 bytes on Linux from the Fx Pak Pro, it splits out the requests into 128 byte chunks that are sent over multiple responses. No where is this documented. :)
> Fix usb2snes fxpak pro issue on Linux

- src/Randomizer.SMZ3/Generation/StandardFiller.cs
Phiggle found an issue where if you manually place a super missile at a location, the generator will crash. This is because when it places a super missile at a given location, it pulls from the progression list of items. When it tries to place a super missile in sphere 1, it also tries to pull from the list of progression items.
> Fix manual super missile placement

- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.SMZ3.Tracking/VoiceCommands/MsuModule.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/RandomizerTests.cs
Basically, if someone used the MSU Randomizer to generate a MSU before opening tracker, she would read the YML on launch even if the person specified no MSU. I'm removing this functionality entirely of reading the MSU if no MSU is specified in SMZ3.
This also fixes the unit test differences between Windows and other operating systems.
> Fix Conflicts With MSU Randomizer

- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.SMZ3/Generation/SpritePatcherService.cs
This handles cases where weirdos like me who always leave the default sprites selected were getting blank names in hints after closing and restarting Tracker. This may have something to do with the default sprites not having their paths saved in `randomizer-options.yml`?
Closes #452
> #452: Added failsafe for blank sprite names

- src/Randomizer.SMZ3/Generation/StandardFiller.cs
Fixes #486
I don't think this ever actually worked fully. lol Two main issues. The progression item pool was not randomized, so it always picked the first item in the list. Secondly, I got rid of junk progression items (such as the 300 rupees) to increase the likelihood of a genuine required progression item is there. It's still not 100% required, though.
> Fix progression item location option

- src/Randomizer.SMZ3.Tracking/AutoTracking/GameService.cs
At least, I think. If this wants to loop over the whole `0x600` span, it needs to go until `0x180`.
> Fixed range of item-counting loop

- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.Data/WorldData/Regions/SuperMetroid/Norfair/UpperNorfairWest.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/LocationLogicTests.cs
- tests/Randomizer.SMZ3.Tests/LogicTests/RandomizerTests.cs
This technically changes the logic a tiny bit, so maybe we should wait until the next version? I set the version number to 9.8.1, in anticipation of that conclusion.
> Require bombs to leave Hi Jump Lobby Missile

- src/Randomizer.Abstractions/TrackerBase.cs
- src/Randomizer.App/Windows/TrackerWindow.xaml.cs
- src/Randomizer.Data/Configuration/ConfigFiles/ResponseConfig.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/ZeldaStateChecks/PegWorld.cs
- src/Randomizer.SMZ3.Tracking/Tracker.cs
So this didn't feel *great*, but it worked. I wanted to encapsulate this check in its own class, but I was having a hard time working out how to get the *difference* between the old value and the new value while also only performing the check while on the Pegworld overworld screen.
Here's what the initial batch of responses would look like, in `Sassy/responses.yml`:
```
PegWorldModePeggedMultiple:
1:
- Text: Pop.
- Text: Poop.
Weight: 0.001
- Text: Plop.
Weight: 0.001
2:
- Text: Popop
3:
- Text: Popopop
4:
- Text: Popopopop
5:
- Text: Popopopopop
6:
- Text: Popopopopopop
7:
- Text: Popopopopopopop
```
I figure we could add rare variants with the same number of syllables, like "papa papa", "Parapa Palace", and "PaRappa the Rapper".
Anyway, let me know if I missed a better way to organize …
> #505: Implemented auto-pegging

- src/Randomizer.CrossPlatform/Views/GenerationSettingsBasicPanel.axaml.cs
- src/Randomizer.Data/Options/Config.cs
- src/Randomizer.Data/RandomizerVersion.cs
- src/Randomizer.Data/Services/GenerationSettingsWindowService.cs
- src/Randomizer.SMZ3/FileData/Patches/MetadataPatch.cs
- src/Randomizer.SMZ3/Generation/RomGenerationService.cs
- src/Randomizer.SMZ3/Generation/Smz3Randomizer.cs
Some of the recent changes made me think this would be a good idea. If someone puts in an old config string into a newer version and presses the button pull in the seed number, it'll throw a warning that the generated seed may not match.
> Verify config string randomizer version

- src/Randomizer.App/Randomizer.App.csproj
- src/Randomizer.CrossPlatform/Services/TrackerMapWindowService.cs
- src/Randomizer.Data/Configuration/ConfigFiles/ItemConfig.cs
- src/Randomizer.Data/Configuration/ConfigTypes/ItemData.cs
- src/Randomizer.SMZ3.Tracking/AutoTracking/MetroidStateChecks/Crocomire.cs
- src/Randomizer.SMZ3/Generation/StandardFiller.cs
- src/Randomizer.Shared/Enums/ItemCategory.cs
- src/Randomizer.Shared/Enums/ItemType.cs
- src/Randomizer.Shared/Enums/ItemTypeExtensions.cs
- Fixes #512 - Auto tracker spoiling keycard type
- Fixes #510 - Tracker states pre-croc announcement without the boss keycard
- Fixes an issue where keycards and Zelda keys would be shown as useless on the map
- Fixes the crossplatform version not showing Super Metroid doors on the map
> Fixes various keysanity issues

- src/TrackerCouncil.Smz3.Chat.Integration/IChatClient.cs
- src/TrackerCouncil.Smz3.Chat.Twitch/TwitchChatClient.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/ChatConfig.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/ChatIntegrationModule.cs
Fixes #167
Needs config PR approved as well: https://github.com/TheTrackerCouncil/SMZ3CasConfigs/pull/18
> Fix reconnecting to Twitch chat

- src/TrackerCouncil.Smz3.Tracking/TrackerCouncil.Smz3.Tracking.csproj
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/MsuModule.cs
Now wondering if we should do a cancel both in the pre-shuffle _and_ the shuffled events. But this works.
> Moved MSU Resume Cancel to new pre-shuffle event

- src/TrackerCouncil.Smz3.Tracking/Tracker.cs
This should make the "popopopopop"s more likely than the singular "pop"s
> #539: Wait for Peg World lines

- src/TrackerCouncil.Smz3.UI/ViewModels/TrackerWindowViewModel.cs
- src/TrackerCouncil.Smz3.UI/Views/TrackerWindow.axaml
- src/TrackerCouncil.Smz3.UI/Views/TrackerWindow.axaml.cs
> Added button to resize tracker window

- src/TrackerCouncil.Smz3.Data/Options/GeneralOptions.cs
- src/TrackerCouncil.Smz3.Data/Services/GitHubSpriteDownloaderService.cs
- src/TrackerCouncil.Smz3.Data/Services/IGitHubSpriteDownloaderService.cs
- src/TrackerCouncil.Smz3.Data/Services/OptionsWindowService.cs
- src/TrackerCouncil.Smz3.UI/Services/MainWindowService.cs
I discovered sprite downloads were messed up. Effectively, on a new install it has a list of files included in the build. Previously what would happen is that it would not download any files, then it would save a null value in the yaml config file. Next time it loaded it would fail because it didn't expect a null value.
I also updated it to save the hashes into a new sprite-hashes.yml file so that it would stop making the main randomizer-options.yml file cleaner.
> Fix sprite downloads

- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/SchrodingersString.cs
- src/TrackerCouncil.Smz3.Tracking/Services/ICommunicator.cs
- src/TrackerCouncil.Smz3.Tracking/Services/SpeakVisemeReachedEventArgs.cs
- src/TrackerCouncil.Smz3.Tracking/Services/SpeechRequest.cs
- src/TrackerCouncil.Smz3.Tracking/Services/TextToSpeechCommunicator.cs
- src/TrackerCouncil.Smz3.Tracking/Tracker.cs
- src/TrackerCouncil.Smz3.UI.Legacy/Windows/MultiplayerConnectWindow.xaml.cs
- src/TrackerCouncil.Smz3.UI/Services/TrackerSpeechWindowService.cs
I won't be able to go through any time soon and really find good lines for this, but I'm going ahead and implementing this. This allows you to change the images that are used for tracker. Currently there are three reactions: default, WTF, and bored. Once tracker finishes saying a line, she'll reset back to the default.
It's usable like this in the configs, and the TrackerImage values shouldn't be case sensitive.
```
- Text: <break time='3s'/> Oh I'm sorry. Was I supposed to care about Reserve Tanks?
Weight: 0.5
TrackerImage: Bored
```
Apparently I accidentally committed to the config main branch directly. 😬 [Here's the commit for the config branch](https://github.com/TheTrackerCouncil/SMZ3CasConfigs/commit/8f4d5fe3e1b9acc7d7fb7ab1bf413ca5b339b267)
> Implement tracker reaction images

- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/HintsConfig.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/SpoilerConfig.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/SpoilerModule.cs
I felt like this was missing since I added the hint/spoiler functionality but never actually bothered to change it despite it being such a minor change.
> Sass when enabling hints/spoilers when already enabled

- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/CheatsConfig.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/CheatsModule.cs
Give Tracker the satisfaction she deserves.
> Add specific lines for killing the player, and lines for enabling/disabling cheats when already enabled/disabled.

- src/TrackerCouncil.Smz3.Data.SchemaGenerator/Program.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/BossInfo.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/SpoilerConfig.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Boss.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Location.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/IHasBoss.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Region.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Room.cs
- src/TrackerCouncil.Smz3.Tracking/NaturalLanguage.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerBossService.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/MultiplayerModule.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/SpoilerModule.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/TrackerModule.cs
> Update item spoilers

- src/TrackerCouncil.Smz3.Abstractions/ITrackerGameStateService.cs
- src/TrackerCouncil.Smz3.Data/Options/AutoMapUpdateBehavior.cs
- src/TrackerCouncil.Smz3.Data/Options/GeneralOptions.cs
- src/TrackerCouncil.Smz3.Data/Options/RandomizerOptions.cs
- src/TrackerCouncil.Smz3.Data/Options/TrackerOptions.cs
- src/TrackerCouncil.Smz3.Data/ViewModels/OptionsWindowTrackerOptions.cs
- src/TrackerCouncil.Smz3.Data/ViewModels/OptionsWindowViewModel.cs
- src/TrackerCouncil.Smz3.Tracking/AutoTracking/MetroidStateChecks/ChangedMetroidRegion.cs
- src/TrackerCouncil.Smz3.Tracking/AutoTracking/ZeldaStateChecks/ChangedOverworld.cs
- src/TrackerCouncil.Smz3.Tracking/AutoTracking/ZeldaStateChecks/EnteredDungeon.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerGameStateService.cs
> Add new automatic map transition behavior options

- src/TrackerCouncil.Smz3.UI/Services/SharedCrossplatformService.cs
> Fix crash when with invalid launch applications

- src/TrackerCouncil.Smz3.Data/Configuration/Configs.cs
- src/TrackerCouncil.Smz3.Data/Services/GitHubConfigDownloaderService.cs
- src/TrackerCouncil.Smz3.Data/Services/IGitHubConfigDownloaderService.cs
- src/TrackerCouncil.Smz3.Data/Services/OptionsWindowService.cs
- src/TrackerCouncil.Smz3.UI/Services/MainWindowService.cs
> Update to reload configs after downloading

- src/TrackerCouncil.Smz3.Abstractions/ITrackerBossService.cs
- src/TrackerCouncil.Smz3.Abstractions/ITrackerItemService.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigFiles/ResponseConfig.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Item.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Location.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/IHasBoss.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/IHasLocations.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/IHasTreasure.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Region.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Room.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerBossService.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerItemService.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerLocationService.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/BossTrackingModule.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/GrammarBuilder.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/ItemTrackingModule.cs
Goal here is to still have some tracker sass when she mishears things, but hopefully lower the amount of scenarios where people don't realize that tracker did something until later.
Fixes #586
Fixes #585
> Add sass when tracking things that are likely misheard

- src/TrackerCouncil.Smz3.Data/Options/Sprite.cs
- src/TrackerCouncil.Smz3.Data/Options/SpriteFilter.cs
- src/TrackerCouncil.Smz3.Data/RandomizerDirectories.cs
- src/TrackerCouncil.Smz3.Data/Services/SpriteService.cs
- src/TrackerCouncil.Smz3.Data/Services/TrackerSpriteService.cs
- src/TrackerCouncil.Smz3.Data/TrackerCouncil.Smz3.Data.csproj
- src/TrackerCouncil.Smz3.Data/ViewModels/SpriteViewModel.cs
- src/TrackerCouncil.Smz3.Tracking/Services/UIService.cs
- src/TrackerCouncil.Smz3.UI/Services/SoloRomListService.cs
- src/TrackerCouncil.Smz3.UI/Services/TrackerMapWindowService.cs
- src/TrackerCouncil.Smz3.UI/Services/TrackerSpeechWindowService.cs
- src/TrackerCouncil.Smz3.UI/ViewModels/TrackerMapWindowViewModel.cs
- src/TrackerCouncil.Smz3.UI/Views/GenerationSettingsBasicPanel.axaml.cs
- src/TrackerCouncil.Smz3.UI/Views/SpriteWindow.axaml
- src/TrackerCouncil.Smz3.UI/Views/SpriteWindow.axaml.cs
Closes #611 
This also compresses a bit of the UI for the sprites to fit more into the window since we have so many Z3 sprites now.
> Add button to sprite window to upload sprites

- .github/workflows/dotnet.yml
- docs/ReleaseNotes.md
- setup/LinuxBuildZipper.ps1
- setup/package-macos-app.sh
- setup/randomizer.app.iss
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/AutotrackerConfig.cs
- src/TrackerCouncil.Smz3.Data/RandomizerDirectories.cs
- src/TrackerCouncil.Smz3.Data/Services/GitHubFileSynchronizerService.cs
- src/TrackerCouncil.Smz3.Data/Tracking/AutoTrackerMetroidState.cs
- src/TrackerCouncil.Smz3.Tracking/AutoTracking/AutoTracker.cs
- src/TrackerCouncil.Smz3.Tracking/AutoTracking/AutoTrackerModules/GameMonitor.cs
- src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj
- src/TrackerCouncil.Smz3.UI/Views/SetupWindow.axaml
- Updated version to RC 1
- Adds tracker sprites to packaged versions
- Fix sprite syncing when the folder doesn't already exist
- Force a full detection of if the player is playing the game on a disconnect. This should hopefully help limit issues that could arise when switching games when doing something like a multi game randomizer using Archipelago like Pink did a while back
- Wait a couple seconds after connecting to the emulator verify that the connection is solid, then stop trying to connect if it detects it's in a disconnect/reconnect loop. This is way more reliable than it used to be, so anymore the situation only seems to arise when the either the connecting application (usually SNI) craps out or if the player is in a different game like Super Metroid. (Fixes #252). Tracker will …
> Upgrade fixes

- src/TrackerCouncil.Smz3.Abstractions/ITrackerBossService.cs
- src/TrackerCouncil.Smz3.Data/TrackerCouncil.Smz3.Data.csproj
- src/TrackerCouncil.Smz3.Data/ViewModels/OptionsWindowTwitchIntegration.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/IHasReward.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Region.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/CastleTower.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/DesertPalace.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/EasternPalace.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/GanonsTower.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/HyruleCastle.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/IcePalace.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/MiseryMire.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/PalaceOfDarkness.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/SkullWoods.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/SwampPalace.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/ThievesTown.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/TowerOfHera.cs
- src/TrackerCouncil.Smz3.Data/WorldData/Regions/Zelda/TurtleRock.cs
- src/TrackerCouncil.Smz3.LegacyLogic/LegacyWorld.cs
- src/TrackerCouncil.Smz3.SeedGenerator/FileData/Patches/LocationsPatch.cs
- src/TrackerCouncil.Smz3.Shared/Multiplayer/MultiplayerVersion.cs
- src/TrackerCouncil.Smz3.Tracking/AutoTracking/ZeldaStateChecks/ViewedText.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerItemService.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerLocationService.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/BossTrackingModule.cs
- src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj
- src/TrackerCouncil.Smz3.UI/ViewModels/TrackerWindowDungeonPanelViewModel.cs
- Fix #644 where SMZ3 would crash on refresh profiles
- Fix issue with dungeon items not being tracked in parsed roms
- Updated auto tracking to clear locations even if item tracking fails (happens with cheats and AP seeds with starting items)
- Updated Pyramid Fairy showing logic incorrectly in AP seeds
- Fix issue where Aga was not being marked by default
- Fix issue where tracker would say the whole line about needing the player to say please when marking as defeated without damage
- Updated verbiage for the chat greeting time limit
- Fix #635 where viewing the bomb merchant would not mark the red crystals
- Fix issue with some locations being stated to be out of logic (hopefully)
> Fixes for 9.9.0 release

- src/TrackerCouncil.Smz3.UI/Services/TrackerLocationsWindowService.cs
- src/TrackerCouncil.Smz3.UI/TrackerCouncil.Smz3.UI.csproj
I know we've had lots of small releases lately, but I'm going to create a build for this as I think this will probably hit Pink when she gets back to SMZ3 in her AP async. I think it is likely to hit other people playing SMZ3 in the async AP going on right now.
> Fix reloading when there are no remaining locations

- src/TrackerCouncil.Smz3.Data/WorldData/World.cs
- src/TrackerCouncil.Smz3.LegacyLogic/LegacyWorldState.cs
- src/TrackerCouncil.Smz3.LegacyLogic/Regions/Zelda/LegacyMiseryMire.cs
- src/TrackerCouncil.Smz3.LegacyLogic/Regions/Zelda/LegacyTurtleRock.cs
- src/TrackerCouncil.Smz3.Tracking/TrackingServices/TrackerPrerequisiteService.cs
This fixes an issue where MM/TR would sometimes appear as in logic when they shouldn't be.
> Fix AP required medallion tracking

- src/TrackerCouncil.Smz3.Abstractions/TrackerBase.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigFiles/TrackerProfileConfig.cs
- src/TrackerCouncil.Smz3.Data/Options/GeneralOptions.cs
- src/TrackerCouncil.Smz3.Data/Options/TrackerOptions.cs
- src/TrackerCouncil.Smz3.Data/Options/TrackerSpeechReactionImages.cs
- src/TrackerCouncil.Smz3.Data/Services/TrackerSpriteService.cs
- src/TrackerCouncil.Smz3.Tracking/Services/ICommunicator.cs
- src/TrackerCouncil.Smz3.Tracking/Services/TextToSpeechCommunicator.cs
- src/TrackerCouncil.Smz3.Tracking/Tracker.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/GoModeModule.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/GoalModule.cs
This is a new config that can be bundled with tracker sprite packs that can modify the default voice used and add custom voice lines.
> Allow tracker sprite packs to have configs

- src/TrackerCouncil.Smz3.UI/Views/TrackerLocationsWindow.axaml
Really thought we had a bug for this. But, this fixes an issue where the scrollable list of regions would be super small because of a lot of pinned locations and hint tiles. This makes the full window scrollable.
> Update locations window to have a full window scrollbar

- src/TrackerCouncil.Smz3.Data/Configuration/ConfigFiles/GameLinesConfig.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigFiles/HintTileConfig.cs
- src/TrackerCouncil.Smz3.Data/Configuration/ConfigTypes/HintsConfig.cs
- src/TrackerCouncil.Smz3.Data/Services/IMetadataService.cs
- src/TrackerCouncil.Smz3.Data/Services/MetadataService.cs
- src/TrackerCouncil.Smz3.SeedGenerator/Generation/GameHintService.cs
- src/TrackerCouncil.Smz3.SeedGenerator/Infrastructure/PlaythroughService.cs
- src/TrackerCouncil.Smz3.Shared/Enums/LocationUsefulness.cs
- src/TrackerCouncil.Smz3.Tracking/Tracker.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/ChatIntegrationModule.cs
- src/TrackerCouncil.Smz3.Tracking/VoiceCommands/SpoilerModule.cs
- src/TrackerCouncil.Smz3.UI/Services/OptionsWindowService.cs
- src/TrackerCouncil.Smz3.UI/Services/TrackerSpeechWindowService.cs
- src/TrackerCouncil.Smz3.UI/Views/OptionsWindow.axaml
- src/TrackerCouncil.Smz3.UI/Views/OptionsWindow.axaml.cs
- src/TrackerCouncil.Smz3.UI/Views/SetupWindow.axaml.cs
Fixes #696 - Hints for where items aren't will now refer to the area with the most accessible uncleared locations.
Fixes #695 - This will pull in the new region hints that should avoid potentially misleading hints.
Fixes #694 - When disconnected from Twitch, Tracker will check to see if you've reconnected after 15 seconds before mentioning being disconnected.
Fixes #689 - When playing keysanity, mandatory locations with keys or keycards are double checked to see if it's only the key/keycard that is mandatory so that it will provide alternative text.
Fixes #687 - Adds back a random chance of Mr. Smooth being used if the "Default" profile is being used.
Fixes #685 - The initial setup window now saves upon each click of the next button, so if people close with the x button it'll preserve …
> Various Fixes and Updates

- src/TrackerCouncil.Smz3.Data/Options/Sprite.cs
- src/TrackerCouncil.Smz3.Data/Services/SpriteService.cs
I noticed during testing that the custom sprite copying didn't work as expected because apparently I made it so custom sprites weren't added to subdirectories for each sprite type. Updated custom sprites to be categorized into Link/Samus/Ships subfolders like the default sprites and fixed the sprite initialization to actually copy over the user's old custom sprites.
> Update custom sprites to be categorized
